import React,{useEffect,useState} from 'react';
import {View,Pressable,StyleSheet,useWindowDimensions,ActivityIndicator,BackHandler,Platform} from 'react-native';
import {SafeAreaProvider,SafeAreaView,useSafeAreaInsets} from 'react-native-safe-area-context';
import {StatusBar} from 'expo-status-bar';
import {useFonts} from 'expo-font';
import {Outfit_600SemiBold} from '@expo-google-fonts/outfit';
import {Figtree_400Regular,Figtree_600SemiBold} from '@expo-google-fonts/figtree';
import {ComicNeue_400Regular} from '@expo-google-fonts/comic-neue';
import {AppProvider,useApp} from './src/state/AppProvider';
import {T,Icon,IconButton,Row} from './src/components/UI';
import {TodayScreen} from './src/screens/TodayScreen';
import {OnboardingScreen} from './src/screens/OnboardingScreen';
import {LearningPathScreen,TrainScreen,ProgressScreen,SettingsScreen,ProfileScreen} from './src/screens/LibraryScreens';
import {LibraryEditor} from './src/screens/LibraryEditor';
import {TrainingScreen} from './src/screens/TrainingScreen';
import {colors,fonts,ui} from './src/design';
import type {AppActions,TabId,TrainingRequest} from './src/types';
const tabs:{id:TabId;label:string;icon:string}[]=[{id:'today',label:'Vandaag',icon:'sun'},{id:'path',label:'Leerweg',icon:'path'},{id:'train',label:'Trainen',icon:'train'},{id:'progress',label:'Voortgang',icon:'chart'}];
type Overlay='library'|'settings'|'profile'|null;
function AppShell(){const {state,ready,storageError}=useApp();const [tab,setTab]=useState<TabId>('today');const [overlay,setOverlay]=useState<Overlay>(null);const [training,setTraining]=useState<TrainingRequest|null>(null);const wide=useWindowDimensions().width>=760;const insets=useSafeAreaInsets();
 useEffect(()=>{const sub=BackHandler.addEventListener('hardwareBackPress',()=>{if(training)return true;if(overlay){setOverlay(null);return true;}if(tab!=='today'){setTab('today');return true;}return false;});return()=>sub.remove();},[overlay,tab,training]);
 const actions:AppActions={onStart:(request)=>{setTraining(request);setOverlay(null);},onTab:(value)=>{setTab(value);setOverlay(null);},onLibrary:()=>setOverlay('library'),onSettings:()=>setOverlay('settings'),onProfile:()=>setOverlay('profile')};
 if(!ready)return <View style={s.loading}><ActivityIndicator color={colors.accent}/><T variant="caption">Je leesplek wordt klaargezet…</T></View>;
 const nav=(desktop:boolean)=><View style={desktop?s.desktopTabs:s.tabs} accessibilityRole="tablist">{tabs.map(t=><Pressable key={t.id} accessibilityRole="tab" accessibilityLabel={t.label} accessibilityState={{selected:tab===t.id&&!overlay}} onPress={()=>actions.onTab(t.id)} style={({pressed})=>[desktop?s.desktopTab:s.tab,{opacity:pressed?.6:1},desktop&&tab===t.id&&!overlay?{backgroundColor:ui.forestSoft}:null]}><View style={!desktop&&tab===t.id&&!overlay?s.activeIcon:undefined}><Icon name={t.icon} size={desktop?19:23} color={tab===t.id&&!overlay?colors.accent:ui.dim}/></View><T variant="caption" color={tab===t.id&&!overlay?colors.accent:ui.dim} style={{fontFamily:tab===t.id&&!overlay?fonts.strong:fonts.body,fontSize:desktop?14:11}}>{t.label}</T></Pressable>)}</View>;
 if(training)return <SafeAreaView edges={['top','bottom']} style={{flex:1,backgroundColor:colors.bg}}><StatusBar style="dark"/><TrainingScreen key={JSON.stringify(training)} request={training} onClose={()=>{setTraining(null);setTab('today');}} onProfile={()=>{setTraining(null);setOverlay('profile');}}/></SafeAreaView>;
 return <SafeAreaView edges={['top']} style={{flex:1,backgroundColor:ui.page}}><StatusBar style="dark"/><View style={s.header}><View style={s.headerInner}><Pressable onPress={()=>actions.onTab('today')} accessibilityLabel="Snellezer, naar vandaag" accessibilityRole="button" style={{flexDirection:'row',alignItems:'center',gap:10,minHeight:44}}><View style={s.logo}><View style={[s.logoLine,{opacity:.45}]}/><View style={[s.logoLine,{backgroundColor:colors.sun,width:20}]}/><View style={[s.logoLine,{opacity:.45,width:12}]}/></View><T variant="heading" style={{fontSize:24,letterSpacing:-.6}}>snellezer<T color={colors.accent} style={{fontSize:24}}>.</T></T></Pressable>{wide&&state.profile.onboardingComplete&&nav(true)}<Row><IconButton name="settings" label="Leesinstellingen" onPress={actions.onSettings} style={{backgroundColor:'transparent'}}/><IconButton name="user" label="Mijn leesplek" onPress={actions.onProfile} style={{backgroundColor:ui.forestSoft}}/></Row></View></View>
 {!!storageError&&<View style={{padding:12,backgroundColor:colors.tintSun}}><T variant="caption" accessibilityRole="alert">{storageError}</T></View>}
 {!state.profile.onboardingComplete&&!overlay?<OnboardingScreen onComplete={()=>setTraining({exerciseId:'baseline',baseline:true})} onExplore={()=>setTab('today')}/>:overlay==='library'?<LibraryEditor actions={actions} onBack={()=>setOverlay(null)}/>:overlay==='settings'?<SettingsScreen actions={actions} onBack={()=>setOverlay(null)}/>:overlay==='profile'?<ProfileScreen actions={actions} onBack={()=>setOverlay(null)}/>:tab==='today'?<TodayScreen actions={actions}/>:tab==='path'?<LearningPathScreen actions={actions}/>:tab==='train'?<TrainScreen actions={actions}/>:<ProgressScreen actions={actions}/>}
 {!wide&&state.profile.onboardingComplete&&<View style={{paddingBottom:Math.max(insets.bottom,8),backgroundColor:colors.bg,borderTopWidth:1,borderTopColor:ui.line}}>{nav(false)}</View>}
 </SafeAreaView>;
}
export default function App(){const [loaded,error]=useFonts({Outfit_600SemiBold,Figtree_400Regular,Figtree_600SemiBold,ComicNeue_400Regular,OpenDyslexic:require('./assets/OpenDyslexic-Regular.otf')});return <SafeAreaProvider>{loaded||error?<AppProvider><AppShell/></AppProvider>:<View style={s.loading}><ActivityIndicator color={colors.accent}/></View>}</SafeAreaProvider>;}
const s=StyleSheet.create({loading:{flex:1,alignItems:'center',justifyContent:'center',gap:18,backgroundColor:ui.page},header:{borderBottomWidth:1,borderBottomColor:ui.line,backgroundColor:colors.bg},headerInner:{width:'100%',maxWidth:1128,alignSelf:'center',minHeight:80,paddingHorizontal:24,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},logo:{width:34,height:34,borderRadius:11,backgroundColor:colors.accent,justifyContent:'center',alignItems:'center',gap:4},logoLine:{height:3,width:19,borderRadius:2,backgroundColor:colors.bg},desktopTabs:{flexDirection:'row',alignItems:'center',gap:8},desktopTab:{flexDirection:'row',gap:8,alignItems:'center',paddingHorizontal:17,paddingVertical:11,borderRadius:24,minHeight:44},tabs:{flexDirection:'row',paddingTop:8,paddingHorizontal:12},tab:{flex:1,minHeight:61,alignItems:'center',justifyContent:'center',gap:5},activeIcon:{backgroundColor:ui.forestSoft,borderRadius:20,paddingHorizontal:16,paddingVertical:4,marginVertical:-4}});
