export type SkillId = 'snelheid' | 'begrip' | 'blikveld' | 'focus';
export type TabId = 'today' | 'path' | 'train' | 'progress';
export type ExerciseMode = 'rsvp' | 'chunks' | 'forward' | 'fixation' | 'reading' | 'scan' | 'peripheral' | 'eye' | 'groups' | 'rhythm' | 'relax' | 'paper' | 'wordflash' | 'catcher' | 'sprint';
export type Question = { question: string; options: string[]; answer: number };
export type Passage = { id: string; title: string; text: string; questions: Question[]; child?: boolean };
export type Exercise = { id: string; title: string; subtitle: string; description: string; skill: SkillId; mode: ExerciseMode; minutes: number; icon: string };
export type Profile = { name: string; ageGroup: 'child' | 'teen' | 'adult'; goal: 'study' | 'work' | 'pleasure'; onboardingComplete: boolean };
export type ReadingSettings = { enabled: boolean; font: 'standard' | 'dyslexic' | 'comic'; fontSize: number; letterSpacing: number; wordSpacing: number; lineHeight: number; overlay: 'none' | 'cream' | 'blue' | 'green' | 'pink' | 'lilac'; overlayOpacity: number; background: 'white' | 'cream' | 'dark' | 'gray'; bionic: boolean; syllables: boolean; lineGuide: boolean };
export type SessionResult = { id: string; exerciseId: string; skill: SkillId; wpm: number; comprehension: number | null; words: number; durationSeconds: number; date: string; xp: number; dailyId?: string };
export type SavedText = { id: string; title: string; text: string; createdAt: string };
export type AppState = { profile: Profile; settings: ReadingSettings; sessions: SessionResult[]; texts: SavedText[]; targetWpm: number; kidsMode: boolean; baseline: { wpm: number; comprehension: number } | null; };
export type TrainingRequest = { exerciseId: string; daily?: boolean; baseline?: boolean; text?: SavedText };
export type AppActions = { onStart: (request: TrainingRequest) => void; onTab: (tab: TabId) => void; onLibrary: () => void; onSettings: () => void; onProfile: () => void; };
