import React,{useState} from 'react';
import {View,Pressable,useWindowDimensions} from 'react-native';
import {Screen,T,Button,Card,Icon,Row,ProgressBar} from '../components/UI';
import {Illustration} from '../components/Illustration';
import {colors,ui} from '../design';
import {useApp} from '../state/AppProvider';
import type {Profile} from '../types';
export function OnboardingScreen({onComplete,onExplore}:{onComplete:()=>void;onExplore:()=>void}){
 const {state,updateProfile,setKidsMode}=useApp();const [step,setStep]=useState(0);const [age,setAge]=useState<Profile['ageGroup']>('adult');const [goal,setGoal]=useState<Profile['goal']>('pleasure');const {width,height}=useWindowDimensions();const wide=width>=760;const hero=Math.round(Math.max(170,Math.min(wide?380:300,height*.3)));
 const complete=()=>{updateProfile({ageGroup:age,goal,onboardingComplete:true});setKidsMode(age==='child');onComplete();};
 return <Screen style={{maxWidth:960,paddingTop:wide?60:20}} footer={step===0?<View style={{alignItems:'center',gap:4}}><Button title="Vind mijn leesritme" icon="arrow" onPress={()=>setStep(1)} style={{width:'100%',maxWidth:420}}/><Pressable accessibilityRole="button" onPress={()=>{updateProfile({onboardingComplete:true});onExplore();}} style={{padding:12,minHeight:44}}><T variant="label" color={ui.muted}>Eerst even rondkijken</T></Pressable></View>:<View style={{alignItems:'center',gap:4,width:'100%',maxWidth:520,alignSelf:'center'}}><Button title={step===1?'Ga verder':'Ontdek mijn vertrekpunt'} icon="arrow" onPress={()=>step===1?setStep(2):complete()} style={{alignSelf:'stretch'}}/><Pressable accessibilityRole="button" onPress={()=>setStep(step-1)} style={{padding:12,minHeight:44}}><T variant="label" color={ui.muted}>Vorige stap</T></Pressable></View>}><Row style={{gap:6,maxWidth:140,alignSelf:'center',marginBottom:12}}>{[0,1,2].map(i=><ProgressBar key={i} value={i<=step?1:0} style={{flex:1,height:4}}/>)}</Row>
 {step===0?<View style={{alignItems:'center',gap:22}}><Illustration name="hero" size={hero}/><T variant="eyebrow" color={colors.accent}>WELKOM BIJ SNELLEZER</T><T variant="display" style={{textAlign:'center',fontSize:wide?48:37,lineHeight:wide?54:43}}>Een beetje rust.{'\n'}Een wereld aan woorden.</T><T color={ui.muted} style={{textAlign:'center',maxWidth:420}}>Maak ruimte voor fijner lezen. Met korte oefeningen, op een tempo dat bij jou past.</T><T variant="caption">Zonder account. Gewoon een moment voor jou.</T></View>:
 <View style={{gap:24,maxWidth:520,width:'100%',alignSelf:'center'}}><T variant="eyebrow">EVEN KENNISMAKEN · {step} VAN 2</T><T variant="display" style={{fontSize:36,lineHeight:42}}>{step===1?'In welke levensfase\nlees jij?':'Waar lees je\nhet liefst voor?'}</T><T color={ui.muted}>{step===1?'Dan passen we de teksten en het tempo op je aan.':'We helpen je een gewoonte te maken die bij je past.'}</T>
 {(step===1?[{id:'child',title:'Tot en met 12 jaar',subtitle:'Kleine verhalen, grote avonturen',ill:'plezier'},{id:'teen',title:'13 tot en met 17 jaar',subtitle:'Meer ruimte voor leren en ontdekken',ill:'studie'},{id:'adult',title:'18 jaar en ouder',subtitle:'Voor alles wat je graag wilt lezen',ill:'werk'}]:[{id:'study',title:'Voor mijn studie',subtitle:'Met meer aandacht de stof in',ill:'studie'},{id:'work',title:'Voor mijn werk',subtitle:'Overzicht in een dag vol informatie',ill:'werk'},{id:'pleasure',title:'Voor mijn plezier',subtitle:'Verdwalen in een goed verhaal',ill:'plezier'}]).map(item=>{const selected=(step===1?age:goal)===item.id;return <Card key={item.id} onPress={()=>step===1?setAge(item.id as Profile['ageGroup']):setGoal(item.id as Profile['goal'])} accessibilityLabel={item.title+(selected?', geselecteerd':'')} style={{flexDirection:'row',alignItems:'center',gap:16,padding:18,borderWidth:2,borderColor:selected?colors.accent:ui.line,backgroundColor:selected?ui.forestSoft:colors.bg}}><Illustration name={item.ill} size={60}/><View style={{flex:1,gap:3}}><T variant="label">{item.title}</T><T variant="caption">{item.subtitle}</T></View><Icon name={selected?'checkcircle':'chevron'} color={selected?colors.accent:ui.dim}/></Card>})}
 </View>}
 </Screen>;
}
