import React from 'react';
import {View,Pressable,StyleSheet,useWindowDimensions} from 'react-native';
import {T,Card,Icon,Button,Pill,ProgressBar,Row,SectionHeading,Screen} from '../components/UI';
import {Illustration} from '../components/Illustration';
import {colors,fonts,ui} from '../design';
import {AppActions} from '../types';
import {useApp,buildDailyPlan,dateKey} from '../state/AppProvider';
export function TodayScreen({actions}:{actions:AppActions}){
 const {state,stats}=useApp();const wide=useWindowDimensions().width>=760;const daily=buildDailyPlan(state);const completed=stats.todaySessions.filter(x=>x.dailyId===dateKey()).length;const hour=new Date().getHours();const greeting=hour<12?'Goedemorgen':hour<18?'Goedemiddag':'Goedenavond';
 return <Screen><Row style={{justifyContent:'space-between'}}><View><T variant="eyebrow" style={{marginBottom:6}}>{new Date().toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'long'})}</T><T variant="heading">{greeting}{state.profile.name?`, ${state.profile.name}`:''}.</T></View><Pill icon="flame" label={`${stats.streak} ${stats.streak===1?'dag':'dagen'}`} background={ui.cream} color={ui.forest}/></Row>
 <View style={[s.welcome,{flexDirection:wide?'row':'column'}]}><View style={{flex:1,gap:16,paddingTop:wide?12:0}}><Pill label="EEN KLEIN MOMENT VOOR JEZELF" background="#ECEBDD" color={ui.forest}/><T variant="display" style={{fontSize:wide?48:37,lineHeight:wide?54:43,maxWidth:460}}>Meer uit je woorden.{'\n'}Meer uit je dag.</T><T color={ui.muted} style={{maxWidth:350}}>Een beetje aandacht. Een paar minuten. Ontdek hoeveel fijner lezen kan zijn.</T></View><Illustration name="hero" size={wide?360:275} style={{alignSelf:wide?'center':'flex-end',marginTop:wide?0:-8,marginBottom:-16}}/></View>
 <View style={{flexDirection:wide?'row':'column',gap:20}}><Card style={[s.daily,{flex:wide?1.35:undefined}]}><Row style={{justifyContent:'space-between'}}><Pill label={completed>=3?'GOED GEDAAN':'JOUW DAGELIJKSE MOMENT'} background="#2A574B" color="#DCE9DE"/><View style={s.circle}><T variant="label" color={colors.bg}>{Math.min(completed,3)}<T variant="caption" color="#B8D0C3"> / 3</T></T></View></Row><T variant="heading" color={colors.bg} style={{fontSize:30,lineHeight:36,marginTop:6}}>{completed>=3?'Een mooi moment voor jezelf.':'Kleine stappen,\ngroot leesplezier.'}</T><T color="#C7D9CE" style={{fontSize:15,maxWidth:330}}>{completed>=3?'Je dagsessie zit erop. Morgen staat er weer een nieuw leesmoment voor je klaar.':state.baseline?'Jouw oefeningen staan klaar. Adem even uit en lees op jouw tempo.':'Begin rustig. Drie oefeningen helpen je jouw leesritme te ontdekken.'}</T><Row style={{marginTop:8,marginBottom:6}}><Icon name="clock" size={16} color="#C7D9CE"/><T variant="caption" color="#C7D9CE">Ongeveer 8 min</T><View style={s.dot}/><T variant="caption" color="#C7D9CE">3 oefeningen</T></Row><Button title={completed>=3?'Ontdek meer oefeningen':completed?'Ga verder met je training':'Start mijn dagtraining'} icon="arrow" onPress={()=>completed>=3?actions.onTab('train'):actions.onStart({exerciseId:daily[0].id,daily:true})} style={{backgroundColor:colors.bg}} secondary/><Row style={{justifyContent:'center',marginTop:1}}><Icon name="leaf" size={13} color="#B8D0C3"/><T variant="caption" color="#B8D0C3">Jouw tempo is het goede tempo.</T></Row></Card>
 <View style={{flex:wide?1:undefined,gap:16}}><SectionHeading title="Jouw leesritme" action="Bekijk alles" onPress={()=>actions.onTab('progress')}/><View style={s.stats}><Stat value={stats.averageWpm?String(stats.averageWpm):'—'} label={stats.hasMeasured?'woorden / min':'oefentempo'} icon="zap"/><Stat value={stats.comprehension===null?'—':`${stats.comprehension}%`} label="begrip" icon="book"/><Stat value={String(stats.totalXP)} label="lees-XP" icon="sparkles"/></View><Card style={{flex:1,backgroundColor:ui.subtle,borderWidth:0,padding:22,gap:12}}><Row><View style={s.smallIcon}><Icon name="leaf" color={colors.accent} size={19}/></View><T variant="label">Een fijne gedachte</T></Row><T color={ui.muted} style={{fontSize:15,lineHeight:23}}>Je hoeft niet elk boek sneller te lezen. Soms is aandacht precies wat een verhaal nodig heeft.</T></Card></View></View>
 <SectionHeading title="Verder op jouw manier"/><View style={{flexDirection:wide?'row':'column',gap:16}}><Card onPress={()=>actions.onTab('path')} style={s.explore} accessibilityLabel="Bekijk je leerweg"><Illustration name="leerweg" size={90}/><View style={{flex:1,gap:7}}><T variant="eyebrow">STAP VOOR STAP</T><T variant="heading" style={{fontSize:22}}>Jouw leerweg</T><T variant="caption">Vier weken. Een gewoonte voor jezelf.</T><ProgressBar value={Math.min(stats.completedDays/28,1)} style={{marginTop:5}}/><T variant="caption">{Math.min(stats.completedDays,28)} van 28 leesdagen</T></View><Icon name="chevron" size={18}/></Card><Card onPress={actions.onLibrary} style={s.explore} accessibilityLabel="Lezen met je eigen tekst"><Illustration name="eigen-tekst" size={90}/><View style={{flex:1,gap:7}}><T variant="eyebrow">MAAK HET PERSOONLIJK</T><T variant="heading" style={{fontSize:22}}>Jouw tekst, jouw tempo</T><T variant="caption">Een artikel, een hoofdstuk of iets wat je zelf hebt geschreven.</T></View><Icon name="chevron" size={18}/></Card></View>
 {!state.baseline&&<Pressable onPress={()=>actions.onStart({exerciseId:'baseline',baseline:true})} accessibilityRole="button" style={s.baseline}><Icon name="flag" size={19} color={colors.accent}/><T variant="caption" style={{flex:1}}>Benieuwd naar je vertrekpunt? Doe de begintest.</T><Icon name="arrow" size={18} color={colors.accent}/></Pressable>}
 </Screen>;
}
function Stat({value,label,icon}:{value:string;label:string;icon:string}){return <View style={s.stat}><Icon name={icon} color={ui.muted} size={19}/><T variant="stat" style={{marginTop:7,fontSize:29}}>{value}</T><T variant="caption" style={{fontSize:11}}>{label}</T></View>;}
const s=StyleSheet.create({welcome:{backgroundColor:ui.cream,borderRadius:30,padding:28,overflow:'hidden',gap:4},daily:{backgroundColor:ui.forest,borderWidth:0,gap:13,padding:26},circle:{width:47,height:47,borderRadius:24,borderWidth:3,borderColor:'#789B83',alignItems:'center',justifyContent:'center'},dot:{width:3,height:3,borderRadius:2,backgroundColor:'#C7D9CE',marginHorizontal:3},stats:{flexDirection:'row',gap:10},stat:{backgroundColor:colors.surface,borderRadius:20,padding:16,flex:1,minHeight:130},smallIcon:{width:35,height:35,borderRadius:18,backgroundColor:ui.forestSoft,alignItems:'center',justifyContent:'center'},explore:{flex:1,flexDirection:'row',alignItems:'center',gap:16,padding:22},baseline:{flexDirection:'row',alignItems:'center',gap:12,padding:17,backgroundColor:ui.forestSoft,borderRadius:18}});
