import React,{useEffect,useMemo,useRef,useState} from 'react';
import {View,Pressable,StyleSheet,ScrollView,AppState as NativeAppState,AccessibilityInfo,useWindowDimensions} from 'react-native';
import {T,Button,Card,Icon,IconButton,Row,Pill,ProgressBar,Screen,BackHeader,Stepper,Choice} from '../components/UI';
import {PeripheralStage} from '../components/PeripheralStage';
import {EyeStage,EYE_MODES,type EyeMode} from '../components/EyeStage';
import {Illustration} from '../components/Illustration';
import {ReadingText,overlayColors} from '../components/ReadingText';
import {colors,fonts,ui} from '../design';
import {useApp,buildDailyPlan,createId,dateKey} from '../state/AppProvider';
import {getExercise,PASSAGES,CHILD_PASSAGES,WORD_GAME_ITEMS,WORD_LEVELS,wordLevelSpec,wordsForLevel} from '../data/content';
import {tipForExercise} from '../data/tips';
import type {TrainingRequest,SessionResult,Passage} from '../types';
import {readingBackground} from './LibraryScreens';
type Phase='intro'|'reading'|'quiz'|'result';
const games=['peripheral','groups','wordflash','catcher'];
const paced=['rsvp','chunks','forward','fixation','sprint'];
const rests=['rhythm','relax','eye'];
function shuffle<T>(input:T[]){const a=[...input];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function TrainingScreen({request,onClose,onProfile}:{request:TrainingRequest;onClose:()=>void;onProfile?:()=>void}){
 const app=useApp();const {state,addSession,setBaseline,setTargetWpm}=app;const [plan]=useState(()=>buildDailyPlan(state));const [dailyStep,setDailyStep]=useState(()=>request.daily?Math.min(3,state.sessions.filter(x=>x.dailyId===dateKey()).length):0);const exercise=getExercise(request.daily?plan[Math.min(dailyStep,2)].id:request.exerciseId);
 const [phase,setPhase]=useState<Phase>('intro');const [paused,setPaused]=useState(false);const [confirmExit,setConfirmExit]=useState(false);const [info,setInfo]=useState(false);const [tempo,setTempo]=useState(state.targetWpm);const [cursor,setCursor]=useState(0);const [seconds,setSeconds]=useState(0);const [answers,setAnswers]=useState<Record<number,number>>({});const [questionIndex,setQuestionIndex]=useState(0);const [result,setResult]=useState<SessionResult|null>(null);const [full,setFull]=useState(false);const [message,setMessage]=useState('');const [round,setRound]=useState(0);const [score,setScore]=useState(0);const [revealed,setRevealed]=useState(true);const [roundFeedback,setRoundFeedback]=useState<string|null>(null);const [line,setLine]=useState(0);const [reduceMotion,setReduceMotion]=useState(false);const [animatedWpm,setAnimatedWpm]=useState(0);const [controlsVisible,setControlsVisible]=useState(true);const sessionTip=useMemo(()=>tipForExercise(exercise.id,state.sessions.length),[exercise.id,state.sessions.length]);const [guideAuto,setGuideAuto]=useState(false);const [guideSpeed,setGuideSpeed]=useState(12);const [eyeMode,setEyeMode]=useState<EyeMode>('lr');const [eyeSpeed,setEyeSpeed]=useState(3);const [eyeSeconds,setEyeSeconds]=useState(60);const [chunkSize,setChunkSize]=useState(3);const [wordLevel,setWordLevel]=useState(2);const [spread,setSpread]=useState(60);const [flashMs,setFlashMs]=useState(400);const [bestSpread,setBestSpread]=useState(0);const [anchor,setAnchor]=useState(false);
 const activeMs=useRef(0);const lastTick=useRef(0);const saved=useRef(false);const currentRunId=useRef(createId());const timeout=useRef<ReturnType<typeof setTimeout>|null>(null);const controlTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const [passageSeed,setPassageSeed]=useState(state.sessions.length);
 const passage=useMemo<Passage>(()=>{if(request.text)return {id:request.text.id,title:request.text.title,text:request.text.text,questions:[]};const pool=state.kidsMode||exercise.mode==='sprint'?CHILD_PASSAGES:PASSAGES;const first=pool[(passageSeed+(request.baseline?0:1))%pool.length];if(exercise.id==='long'){const second=pool[(passageSeed+2)%pool.length];return {...first,title:first.title+' & '+second.title,text:first.text+'\n\n'+second.text,questions:[...first.questions.slice(0,2),...second.questions.slice(0,2)]};}return first;},[request.text,request.baseline,passageSeed,state.kidsMode,exercise.id]);
 const words=useMemo(()=>passage.text.trim().split(/\s+/).filter(Boolean),[passage]);const paragraphs=useMemo(()=>passage.text.split(/\n\n/).filter(Boolean),[passage]);const paperLines=useMemo(()=>{const out=[];for(let i=0;i<words.length;i+=12)out.push(words.slice(i,i+12).join(' '));return out;},[words]);const isPaced=paced.includes(exercise.mode),isGame=games.includes(exercise.mode),isRest=rests.includes(exercise.mode);const restLimit=exercise.mode==='eye'?eyeSeconds:60;const chunk=isPaced?chunkSize:1;const chunkRange=['chunks','fixation','forward'].includes(exercise.mode)?{min:2,max:7}:{min:1,max:5};
 const gameItems=useMemo(()=>{const pool=exercise.mode==='wordflash'?wordsForLevel(wordLevel):WORD_GAME_ITEMS;const out=[];while(out.length<10)out.push(...shuffle(pool));return out.slice(0,10);},[passageSeed,wordLevel,exercise.mode]);const item=gameItems[Math.min(round,9)];
 const targetPair=useMemo(()=>{const a=gameItems[Math.min(round,9)].word;const b=gameItems[(round+3)%10].word;return `${a} · ${b}`;},[gameItems,round]);
 const correctOption=isGame&&(exercise.mode==='groups'||exercise.mode==='peripheral')?targetPair:item.word;
 const options=useMemo(()=>shuffle((exercise.mode==='peripheral'||exercise.mode==='groups')?[targetPair,`${item.word} · ${gameItems[(round+5)%10].word}`,`${gameItems[(round+2)%10].word} · ${item.word}`,`${gameItems[(round+1)%10].word} · ${gameItems[(round+6)%10].word}`]:[item.word,...item.distractors.slice(0,3)]),[round,gameItems,targetPair,exercise.mode]);
 const scanTargets=useMemo(()=>shuffle([...new Set(words.map(w=>w.replace(/[^\p{L}]/gu,'')).filter(w=>w.length>5))]).slice(0,5),[words]);const scanTarget=scanTargets[Math.min(round,scanTargets.length-1)];
 const bg=readingBackground(state.settings),dark=state.settings.enabled&&state.settings.background==='dark';const wide=useWindowDimensions().width>=760;
 useEffect(()=>{AccessibilityInfo.isReduceMotionEnabled().then(setReduceMotion);const sub=AccessibilityInfo.addEventListener('reduceMotionChanged',setReduceMotion);return()=>sub.remove();},[]);
 useEffect(()=>{const sub=NativeAppState.addEventListener('change',s=>{if(s!=='active')setPaused(true);});const hide=()=>{if(typeof document!=='undefined'&&document.hidden)setPaused(true);};if(typeof document!=='undefined')document.addEventListener('visibilitychange',hide);return()=>{sub.remove();if(typeof document!=='undefined')document.removeEventListener('visibilitychange',hide);};},[]);
 useEffect(()=>{if(phase!=='reading'||paused)return;lastTick.current=Date.now();const id=setInterval(()=>{const now=Date.now();activeMs.current+=Math.min(now-lastTick.current,500);lastTick.current=now;setSeconds(activeMs.current/1000);},100);return()=>{clearInterval(id);activeMs.current+=Math.min(Math.max(0,Date.now()-lastTick.current),500);};},[phase,paused]);
 useEffect(()=>{if(phase!=='reading'||paused||!isPaced)return;const id=setTimeout(()=>{const next=cursor+chunk;if(next>=words.length){setCursor(words.length);finishReading(true);}else setCursor(next);},60000/tempo*Math.min(chunk,words.length-cursor));return()=>clearTimeout(id);},[phase,paused,cursor,tempo,exercise.id]);
 useEffect(()=>{if(phase!=='reading'||paused||exercise.mode!=='paper'||!guideAuto)return;const id=setTimeout(()=>{if(line>=paperLines.length-1)finishReading(true);else setLine(line+1);},guideSpeed*100);return()=>clearTimeout(id);},[phase,paused,exercise.mode,guideAuto,guideSpeed,line,paperLines.length]);
 useEffect(()=>{if(phase==='reading'&&!paused&&isRest&&seconds>=restLimit)saveResult(null,true,0);},[seconds,phase,paused,restLimit]);
 useEffect(()=>{if(phase!=='reading'||!isGame||paused||roundFeedback||exercise.mode==='peripheral')return;setRevealed(true);if(exercise.mode==='catcher')return;const id=setTimeout(()=>setRevealed(false),exercise.mode==='wordflash'?wordLevelSpec(wordLevel).flashMs:state.kidsMode?1800:1400);return()=>clearTimeout(id);},[round,phase,paused,exercise.mode,roundFeedback,wordLevel]);
 useEffect(()=>{if(phase!=='reading'||exercise.mode!=='peripheral'||paused||roundFeedback)return;setAnchor(true);setRevealed(false);const fixate=setTimeout(()=>setRevealed(true),700);const flash=setTimeout(()=>{setRevealed(false);setAnchor(false);},700+flashMs);return()=>{clearTimeout(fixate);clearTimeout(flash);};},[round,phase,paused,roundFeedback,flashMs,exercise.mode]);
 useEffect(()=>{setChunkSize(['chunks','fixation','forward'].includes(exercise.mode)?3:1);},[exercise.id]);
 useEffect(()=>()=>{if(timeout.current)clearTimeout(timeout.current);if(controlTimer.current)clearTimeout(controlTimer.current);},[]);
 useEffect(()=>{if(phase!=='result'||!result)return;const goal=result.wpm;if(reduceMotion){setAnimatedWpm(goal);return;}const start=Date.now();const id=setInterval(()=>{const t=Math.min(1,(Date.now()-start)/750);setAnimatedWpm(Math.round(goal*(1-Math.pow(1-t,3))));if(t>=1)clearInterval(id);},25);return()=>clearInterval(id);},[phase,result,reduceMotion]);
 function revealControls(){setControlsVisible(true);if(controlTimer.current)clearTimeout(controlTimer.current);if(!paused)controlTimer.current=setTimeout(()=>setControlsVisible(false),3000);}
 function start(){setPhase('reading');setPaused(false);setCursor(0);setLine(0);setSeconds(0);setAnswers({});setQuestionIndex(0);setRound(0);setScore(0);setResult(null);setMessage('');setFull(false);saved.current=false;activeMs.current=0;currentRunId.current=createId();revealControls();}
 function finishReading(complete:boolean){if(saved.current)return;const dur=activeMs.current/1000;if(dur<3){setMessage('Neem rustig de tijd om de tekst te lezen.');return;}setFull(complete);setPaused(false);if(complete&&passage.questions.length&&exercise.mode!=='scan'){setPhase('quiz');setAnswers({});setQuestionIndex(0);}else saveResult(null,complete,isPaced?Math.min(words.length,cursor):words.length);}
 function saveResult(comprehension:number|null,complete:boolean,readWords?:number,recognitionScore?:number){if(saved.current)return;const dur=Math.max(.1,activeMs.current/1000);let read=readWords??(complete?words.length:cursor);const measured=exercise.mode==='reading';const wpm=isRest||isGame||exercise.mode==='scan'?0:measured?Math.round(read/dur*60):tempo;
 if(!isRest&&!isGame&&exercise.mode!=='scan'&&(read<10||dur<3)){setMessage('Lees minstens 10 woorden voordat je deze oefening afrondt.');return;}
 saved.current=true;setFull(complete);const r:SessionResult={id:currentRunId.current,exerciseId:exercise.id,skill:exercise.skill,wpm,comprehension,words:Math.max(0,read),durationSeconds:dur,date:new Date().toISOString(),xp:complete?20+(comprehension===null?0:Math.round(comprehension/10)):5,...(complete&&request.daily?{dailyId:dateKey()}:{} )};
 if(request.baseline||exercise.id==='baseline'){if(comprehension!==null)setBaseline({wpm,comprehension});}else if(wpm>0)setTargetWpm(tempo);
 addSession(r);setResult(r);setPhase('result');setPaused(false);if(recognitionScore!==undefined)setScore(recognitionScore);
 }
 function submitAnswer(value:number){const next={...answers,[questionIndex]:value};setAnswers(next);if(questionIndex+1<passage.questions.length)setQuestionIndex(questionIndex+1);else{const correct=passage.questions.reduce((n,q,i)=>n+(next[i]===q.answer?1:0),0);saveResult(Math.round(correct/passage.questions.length*100),true,words.length);}}
 function gameAnswer(option:string){if(roundFeedback||paused)return;const correct=option===correctOption;const nextScore=score+(correct?1:0);setScore(nextScore);if(exercise.mode==='peripheral'){if(correct)setBestSpread(b=>Math.max(b,spread));setSpread(v=>Math.max(20,Math.min(95,v+(correct?5:-5))));}setRoundFeedback(correct?'Goed gezien.':`Het was: ${correctOption}`);timeout.current=setTimeout(()=>{setRoundFeedback(null);if(round>=9)saveResult(null,true,10,nextScore);else setRound(round+1);},900);}
 function scanAnswer(word:string){if(paused)return;if(word.replace(/[^\p{L}]/gu,'')===scanTarget){if(round+1>=scanTargets.length)saveResult(null,true,scanTargets.length);else setRound(round+1);setMessage('');}else setMessage('Bijna. Zoek het woord '+scanTarget+'.');}
 function next(){setDailyStep(dailyStep+1);setPhase('intro');setPassageSeed(passageSeed+1);setResult(null);saved.current=false;setMessage('');}
 function quit(){if(phase==='reading'||phase==='quiz'){setPaused(true);setConfirmExit(true);}else onClose();}
 const sessionLabel=request.daily?`DAGTRAINING · ${Math.min(dailyStep+1,3)} VAN 3`:request.baseline?'JOUW VERTREKPUNT':'EEN MOMENT VOOR JEZELF';
 if(request.daily&&dailyStep>=3)return <Screen style={{maxWidth:620,alignItems:'center',paddingTop:70}}><Illustration name="resultaat-hero" size={180}/><T variant="title">Je dagsessie zit erop.</T><T color={ui.muted}>Morgen staat er weer een nieuwe voor je klaar.</T><Button title="Terug naar vandaag" onPress={onClose}/></Screen>;
 if(phase==='intro')return <Screen style={{maxWidth:680}}><BackHeader title={request.daily?'Jouw dagtraining':exercise.title} onBack={onClose}/><View style={{alignItems:'center',gap:21,paddingVertical:20}}><Pill label={sessionLabel}/><Illustration name={exercise.skill==='focus'?'focus':exercise.skill} size={160}/><T variant="display" style={{fontSize:38,lineHeight:43,textAlign:'center'}}>{request.text?request.text.title:exercise.title}</T><T color={ui.muted} style={{textAlign:'center',maxWidth:460}}>{exercise.description}</T><Row><Pill label={`${exercise.minutes} min`} icon="clock" background={colors.surface} color={ui.muted}/><Pill label={request.text?'Eigen tekst':state.kidsMode?'Kort verhaal':'Op jouw tempo'} icon="leaf" background={colors.surface} color={ui.muted}/></Row></View>
 {request.daily&&dailyStep>0&&<Card style={{backgroundColor:colors.tintLilac,borderWidth:0,gap:10}}><Row><Icon name={sessionTip.icon} size={18} color={colors.accent}/><T variant="label">Even tussendoor</T></Row><T variant="heading" style={{fontSize:19}}>{sessionTip.title}</T><T style={{fontSize:15}}>{sessionTip.body}</T><T variant="caption">Neem dit mee in de oefening hierna.</T></Card>}
 {request.daily&&<Card style={{gap:14}}>{plan.map((e,i)=><Row key={i}><View style={{width:30,height:30,borderRadius:15,backgroundColor:i===dailyStep?colors.accent:colors.surface,alignItems:'center',justifyContent:'center'}}>{i<dailyStep?<Icon name="check" size={16} color={colors.accent}/>:<T variant="caption" color={i===dailyStep?colors.bg:ui.muted}>{i+1}</T>}</View><T variant="label" style={{flex:1}}>{e.title}</T><T variant="caption">{e.minutes} min</T></Row>)}</Card>}
 {isPaced&&<Card style={{gap:15,backgroundColor:colors.surface,borderWidth:0}}><Row style={{justifyContent:'space-between'}}><T variant="label">Een prettig oefentempo</T><Icon name="zap" size={19} color={colors.accent}/></Row><Row style={{justifyContent:'center',gap:28}}><IconButton name="minus" label="Tempo verlagen" onPress={()=>setTempo(Math.max(60,tempo-20))}/><View style={{alignItems:'center'}}><T variant="stat">{tempo}</T><T variant="caption">woorden per minuut</T></View><IconButton name="plus" label="Tempo verhogen" onPress={()=>setTempo(Math.min(800,tempo+20))}/></Row></Card>}
 {isPaced&&<Card style={{gap:24,backgroundColor:colors.surface,borderWidth:0}}><Stepper label="Woorden per keer" icon="text" value={chunkSize} unit={chunkSize===1?'woord tegelijk':'woorden tegelijk'} min={chunkRange.min} max={chunkRange.max} step={1} onChange={setChunkSize}/></Card>}
 {exercise.mode==='paper'&&<Card style={{gap:22,backgroundColor:colors.surface,borderWidth:0}}><Choice label="De gids" value={guideAuto?'auto':'zelf'} options={[{value:'zelf',label:'Ik ga zelf verder'},{value:'auto',label:'Loopt vanzelf mee'}]} onChange={v=>setGuideAuto(v==='auto')}/>{guideAuto&&<Stepper label="Tempo van de gids" icon="clock" value={guideSpeed} unit="seconden per regel" min={3} max={30} step={1} onChange={setGuideSpeed} format={v=>(v/10).toFixed(1).replace('.',',')}/>}</Card>}
 {exercise.mode==='eye'&&<Card style={{gap:22,backgroundColor:colors.surface,borderWidth:0}}><Choice label="Patroon" value={eyeMode} options={EYE_MODES} onChange={setEyeMode}/><Stepper label="Snelheid" icon="zap" value={eyeSpeed} unit="van 10" min={1} max={10} step={1} onChange={setEyeSpeed}/><Choice label="Duur" value={String(eyeSeconds)} options={[{value:'60',label:'1 minuut'},{value:'180',label:'3 minuten'},{value:'360',label:'6 minuten'}]} onChange={v=>setEyeSeconds(Number(v))}/></Card>}
 {exercise.mode==='wordflash'&&<Card style={{gap:16,backgroundColor:colors.surface,borderWidth:0}}><Choice label="Niveau" value={String(wordLevel)} options={WORD_LEVELS.map(l=>({value:String(l.level),label:l.title}))} onChange={v=>setWordLevel(Number(v))}/><T variant="caption">Langere woorden krijgen een kortere flits.</T></Card>}
 {exercise.mode==='peripheral'&&<Card style={{gap:24,backgroundColor:colors.surface,borderWidth:0}}><Stepper label="Breedte" icon="eye" value={spread} unit="% van het scherm" min={20} max={95} step={5} onChange={setSpread}/><Stepper label="Flitstijd" value={flashMs} unit="milliseconden" min={120} max={1200} step={40} onChange={setFlashMs}/><T variant="caption">De breedte groeit mee als je goed scoort, en zakt een stapje als het te snel gaat.</T></Card>}
 <Button title={request.baseline?'Start mijn begintest':'Ik ben er klaar voor'} icon="play" onPress={start}/><T variant="caption" style={{textAlign:'center'}}>Je kunt op ieder moment pauzeren.</T></Screen>;
 if(phase==='result'&&result){const dailyMore=request.daily&&full&&dailyStep<2;return <Screen style={{maxWidth:680}}><View style={{alignItems:'center',gap:16,paddingTop:20}}><Pill label={request.daily?`OEFENING ${dailyStep+1} VAN 3`:'MOOI GEDAAN'} icon="check"/><Illustration name="resultaat-hero" size={145}/><T variant="title" style={{textAlign:'center'}}>{full?'Een moment om trots op te zijn.':'Een klein stukje is ook een begin.'}</T><T color={ui.muted} style={{textAlign:'center'}}>{request.baseline?'Dit is jouw vertrekpunt. Van hieruit gaan we rustig verder.':full?'Je hebt aandacht gegeven aan je leesritme. Dat telt.':'Je hebt de oefening eerder afgerond. Je oefentijd is bewaard.'}</T></View>
 <Card style={{backgroundColor:colors.surface,borderWidth:0,alignItems:'center',gap:5,padding:28}}><T variant="display" style={{fontSize:68,lineHeight:76}}>{result.wpm?animatedWpm:isGame?`${score}/10`:exercise.mode==='scan'?scanTargets.length:Math.round(result.durationSeconds)}</T><T variant="caption">{result.wpm?(exercise.mode==='reading'?'woorden per minuut · gemeten':'woorden per minuut · oefentempo'):isGame?(exercise.mode==='peripheral'?`woorden herkend · tot ${bestSpread||spread}% breedte`:'woorden of woordgroepen herkend'):exercise.mode==='scan'?'zoekwoorden gevonden':'seconden rust en aandacht'}</T></Card><Row style={{gap:14}}><Card style={{flex:1,alignItems:'center',gap:5,backgroundColor:ui.subtle,borderWidth:0}}><T variant="stat">{result.comprehension===null?'—':`${result.comprehension}%`}</T><T variant="caption">{result.comprehension===null?'begrip niet gemeten':'tekstbegrip'}</T></Card><Card style={{flex:1,alignItems:'center',gap:5,backgroundColor:ui.subtle,borderWidth:0}}><T variant="stat">+{result.xp}</T><T variant="caption">lees-XP</T></Card></Row>
 <Card style={{backgroundColor:colors.tintLilac,borderWidth:0,gap:10}}><Row><Icon name={sessionTip.icon} size={18} color={colors.accent}/><T variant="label">{sessionTip.title}</T></Row><T style={{fontSize:15}}>{sessionTip.body}</T>{result.comprehension!==null&&<T variant="caption">{result.comprehension<70?'Je oefentempo is een stapje verlaagd, zodat je meer ruimte hebt voor de inhoud.':result.comprehension>=80?'Je nam de inhoud goed mee. Blijf dit tempo volgen zolang het prettig voelt.':'Begrip en tempo zoeken nog hun balans. Dat hoort erbij.'}</T>}</Card>
 {result.comprehension!==null&&passage.questions.some((q,i)=>answers[i]!==q.answer)&&<Card style={{gap:12}}><T variant="label">Even terug naar de inhoud</T>{passage.questions.map((q,i)=>answers[i]!==q.answer?<View key={i} style={{gap:4}}><T variant="caption">{q.question}</T><T variant="label" style={{fontSize:14}}>{q.options[q.answer]}</T></View>:null)}</Card>}
 <Button title={dailyMore?'Verder met mijn volgende oefening':request.daily&&!full?'Probeer deze oefening opnieuw':'Terug naar mijn leesplek'} icon="arrow" onPress={()=>dailyMore?next():request.daily&&!full?setPhase('intro'):onClose()}/>{!state.profile.name&&onProfile&&!dailyMore&&<Button title="Maak mijn leesplek persoonlijk" secondary onPress={onProfile}/>}</Screen>;}
 if(phase==='quiz'){const q=passage.questions[questionIndex];return <Screen style={{maxWidth:680}}><BackHeader title="Wat is je bijgebleven?" onBack={quit}/><ProgressBar value={questionIndex/passage.questions.length}/><Pill label={`VRAAG ${questionIndex+1} VAN ${passage.questions.length}`}/><Illustration name="begrip" size={100}/><T variant="title" style={{fontSize:29,lineHeight:36}}>{q.question}</T><T color={ui.muted}>Kies het antwoord dat volgens jou klopt.</T><View style={{gap:13}}>{q.options.map((o,i)=><Card key={i} onPress={()=>submitAnswer(i)} accessibilityLabel={o} style={{flexDirection:'row',alignItems:'center',gap:14,minHeight:75}}><View style={s.optionCircle}><T variant="label" color={colors.accent}>{String.fromCharCode(65+i)}</T></View><T style={{flex:1}}>{o}</T><Icon name="chevron" size={17} color={ui.dim}/></Card>)}</View>{confirmExit&&<ExitConfirm onCancel={()=>{setConfirmExit(false);setPaused(false);}} onExit={onClose}/>}</Screen>;}
 const progress=isPaced?cursor/words.length:isRest?seconds/60:isGame?round/10:exercise.mode==='scan'?round/scanTargets.length:exercise.mode==='paper'?(line+1)/paperLines.length:0;
 return <View style={{flex:1,backgroundColor:bg}}><View style={{width:'100%',maxWidth:940,alignSelf:'center',flex:1,paddingHorizontal:wide?30:22,paddingTop:18,paddingBottom:18}}><Row style={{marginBottom:14}}><IconButton name="close" label="Oefening sluiten" onPress={quit}/><View style={{flex:1,alignItems:'center',gap:2}}><T variant="label" color={dark?colors.bg:colors.ink}>{exercise.title}</T><T variant="caption">{request.daily?`${dailyStep+1} van 3 · `:''}{Math.floor(seconds/60)}:{String(Math.floor(seconds%60)).padStart(2,'0')}</T></View><IconButton name="info" label="Uitleg over deze oefening" onPress={()=>{setPaused(true);setInfo(true);}}/></Row>
 {isPaced?<Pressable accessibilityLabel="Toon leesbediening" onPress={revealControls} style={{flex:1,justifyContent:'center',alignItems:'center',gap:28,minHeight:250}}>{exercise.mode==='forward'?<View style={{gap:16,alignItems:'center'}}><T color={ui.dim} style={{fontSize:18}}>…</T><ReadingText text={words.slice(cursor,cursor+chunk).join(' ')} settings={state.settings} style={{fontSize:wide?42:30,lineHeight:wide?60:48,textAlign:'center',color:dark?colors.sage:colors.accent}}/><T color={ui.dim} style={{fontSize:18}}>{words.slice(cursor+chunk,cursor+chunk*2).join(' ')}</T></View>:<><View style={s.fixation}/><ReadingText text={words.slice(cursor,cursor+chunk).join(' ')} settings={state.settings} style={{fontSize:state.settings.enabled?state.settings.fontSize+8:wide?42:30,lineHeight:60,textAlign:'center',color:dark?colors.sage:colors.accent}}/><View style={s.fixation}/></>}<T variant="caption" style={{marginTop:32}}>{paused?'Even op adem komen.':`woord ${Math.min(cursor+1,words.length)} van ${words.length}`}</T></Pressable>:
 isRest?<View style={{flex:1,justifyContent:'center',alignItems:'center',gap:28,minHeight:340}}>{exercise.mode==='eye'?<EyeStage mode={eyeMode} speed={eyeSpeed} paused={paused} reduceMotion={reduceMotion}/>:<View style={{width:220,height:220,borderRadius:110,backgroundColor:ui.forestSoft,alignItems:'center',justifyContent:'center',transform:[{scale:reduceMotion?1:.9+Math.sin(seconds*Math.PI/4)*.08}]}}><View style={{width:160,height:160,borderRadius:80,backgroundColor:'#C8DDCC',alignItems:'center',justifyContent:'center'}}><Icon name={exercise.mode==='relax'?'leaf':'heart'} size={45} color={colors.accent}/></View></View>}<T variant="heading" color={dark?colors.bg:colors.ink}>{exercise.mode==='relax'?'Kijk even in de verte.':exercise.mode==='eye'?'Volg rustig het puntje.':seconds%8<4?'Adem rustig in.':'Adem rustig uit.'}</T><T variant="caption">{Math.max(0,restLimit-Math.floor(seconds))} seconden voor jezelf</T></View>:
 isGame?<View style={{flex:1,justifyContent:'center',gap:25,paddingVertical:20}}><T variant="eyebrow" style={{textAlign:'center'}}>RONDE {round+1} VAN 10</T>{roundFeedback?<View style={{minHeight:250,alignItems:'center',justifyContent:'center',gap:18}}><Icon name={roundFeedback==='Goed gezien.'?'checkcircle':'eye'} color={colors.accent} size={48}/><T variant="heading" style={{textAlign:'center'}}>{roundFeedback}</T></View>:exercise.mode==='peripheral'&&anchor?<View style={{minHeight:250,justifyContent:'center',alignItems:'center',gap:8}}><T variant="caption">Houd je blik op het stipje.</T><PeripheralStage left={item.word} right={gameItems[(round+3)%10].word} spread={spread} visible={revealed} dark={dark}/></View>:revealed&&exercise.mode!=='catcher'?<View style={{minHeight:250,justifyContent:'center',alignItems:'center',gap:20}}><T variant="caption">{exercise.mode==='peripheral'?'Houd je blik in het midden.':'Kijk rustig naar de woorden.'}</T><T variant="heading" style={{fontSize:exercise.mode==='peripheral'?25:32,textAlign:'center',letterSpacing:exercise.mode==='peripheral'?3:0}}>{exercise.mode==='peripheral'?`${item.word}    •    ${gameItems[(round+3)%10].word}`:exercise.mode==='groups'?targetPair:item.word}</T></View>:<><T variant="heading" style={{textAlign:'center'}}>{exercise.mode==='catcher'?`Vind het woord: ${item.word}`:'Wat zag je net?'}</T><View style={{gap:12}}>{options.map((o,i)=><Button key={i} title={o} secondary onPress={()=>gameAnswer(o)} disabled={paused}/>)}</View></>}</View>:
 exercise.mode==='scan'?<View style={{flex:1,gap:20}}><Pill label={`ZOEK: ${scanTarget}`} icon="search"/><ScrollView><View style={{flexDirection:'row',flexWrap:'wrap',gap:4}}>{words.map((w,i)=><Pressable key={i} onPress={()=>scanAnswer(w)} accessibilityRole="button" accessibilityLabel={`Kies ${w}`} style={{paddingHorizontal:4,paddingVertical:9,minHeight:44}}><T style={{fontSize:18}}>{w}</T></Pressable>)}</View></ScrollView></View>:
 exercise.mode==='paper'?<View style={{flex:1,gap:18}}><T variant="heading">{passage.title}</T><ScrollView><View style={{gap:16}}>{paperLines.map((p,i)=><View key={i} style={{padding:14,borderRadius:12,backgroundColor:i===line?ui.forestSoft:'transparent',opacity:i<line?.4:1}}><ReadingText text={p} settings={state.settings}/></View>)}</View></ScrollView><Button title={guideAuto?'Klaar met lezen':line===paperLines.length-1?'Laatste regel gelezen':'Volgende regel'} secondary onPress={()=>guideAuto||line===paperLines.length-1?finishReading(true):setLine(line+1)} disabled={paused}/></View>:
 <ScrollView style={{flex:1}} contentContainerStyle={{paddingVertical:24,paddingHorizontal:wide?50:2,gap:22}}><T variant="heading" color={dark?colors.bg:colors.ink}>{passage.title}</T>{paragraphs.map((p,i)=><Pressable key={i} onPress={()=>state.settings.lineGuide&&setLine(i)} style={{padding:state.settings.enabled&&state.settings.lineGuide?12:0,borderRadius:14,backgroundColor:state.settings.enabled&&state.settings.lineGuide&&i===line?ui.forestSoft:'transparent',opacity:state.settings.enabled&&state.settings.lineGuide&&i!==line?.45:1}}><ReadingText text={p} settings={state.settings}/></Pressable>)}</ScrollView>}
 {!!message&&<T variant="caption" color={ui.error} accessibilityRole="alert" style={{padding:12,textAlign:'center'}}>{message}</T>}
 <View style={{gap:16,paddingTop:18,opacity:isPaced&&!controlsVisible&&!paused?.3:1}}><ProgressBar value={progress}/><Row style={{justifyContent:'center',gap:26}}>{isPaced&&<IconButton name="minus" label="Langzamer lezen" onPress={()=>{setTempo(Math.max(60,tempo-20));revealControls();}}/>}<IconButton name={paused?'play':'pause'} label={paused?'Verder lezen':'Pauzeren'} onPress={()=>{setPaused(!paused);setControlsVisible(true);}} style={{width:54,height:54,borderRadius:27,backgroundColor:ui.forestSoft}}/>{isPaced&&<IconButton name="plus" label="Sneller lezen" onPress={()=>{setTempo(Math.min(800,tempo+20));revealControls();}}/>}{isPaced&&<View><T variant="stat" style={{fontSize:26}}>{tempo}</T><T variant="caption">wpm</T></View>}</Row>{!isRest&&!isGame&&exercise.mode!=='scan'&&exercise.mode!=='paper'&&<Button title={isPaced?'Eerder afronden':'Klaar met lezen'} secondary onPress={()=>finishReading(!isPaced)} disabled={paused}/>}</View>
 </View>{state.settings.enabled&&state.settings.overlay!=='none'&&<View pointerEvents="none" style={[StyleSheet.absoluteFill,{backgroundColor:overlayColors[state.settings.overlay],opacity:state.settings.overlayOpacity/100}]}/>}
 {paused&&!confirmExit&&!info&&<View style={s.pauseOverlay}><Card style={{gap:20,alignItems:'center',width:'85%',maxWidth:400}}><Icon name="pause" color={colors.accent} size={36}/><T variant="heading">Even pauze.</T><T variant="caption">Je oefentijd staat stil.</T><Button title="Ik ga weer verder" icon="play" onPress={()=>setPaused(false)} style={{alignSelf:'stretch'}}/><Button title="Stoppen met oefenen" secondary onPress={()=>setConfirmExit(true)} style={{alignSelf:'stretch'}}/></Card></View>}
 {info&&<View style={s.pauseOverlay}><Card style={{width:'85%',maxWidth:450,gap:18}}><T variant="heading">{exercise.title}</T><T>{exercise.description}</T><Button title="Verder met oefenen" onPress={()=>{setInfo(false);setPaused(false);}}/></Card></View>}
 {confirmExit&&<ExitConfirm onCancel={()=>{setConfirmExit(false);setPaused(false);}} onExit={onClose}/>}
 </View>;
}
function ExitConfirm({onCancel,onExit}:{onCancel:()=>void;onExit:()=>void}){return <View style={s.pauseOverlay}><Card style={{width:'85%',maxWidth:420,gap:18}}><T variant="heading">Voor nu genoeg?</T><T color={ui.muted}>Deze oefening is nog niet afgerond en wordt niet bewaard. Eerder voltooide oefeningen blijven staan.</T><Button title="Verder met oefenen" onPress={onCancel}/><Button title="Stop voor nu" secondary onPress={onExit}/></Card></View>;}
const s=StyleSheet.create({fixation:{width:24,height:2,borderRadius:2,backgroundColor:'#B9C8BF'},optionCircle:{width:34,height:34,borderRadius:17,backgroundColor:ui.forestSoft,alignItems:'center',justifyContent:'center'},pauseOverlay:{position:'absolute',top:0,right:0,bottom:0,left:0,backgroundColor:'rgba(15,26,20,.28)',justifyContent:'center',alignItems:'center',zIndex:20}});
