import React,{useEffect,useMemo,useRef,useState} from 'react';
import {View,Pressable,StyleSheet,ScrollView,AppState as NativeAppState,AccessibilityInfo,useWindowDimensions} from 'react-native';
import {T,Button,Card,Icon,IconButton,Row,Pill,ProgressBar,Screen,BackHeader,Stepper,Choice} from '../components/UI';
import {PeripheralStage} from '../components/PeripheralStage';
import {PacedReadingStage} from '../components/PacedReadingStage';
import {EyeStage,EYE_MODES,type EyeMode} from '../components/EyeStage';
import {Illustration} from '../components/Illustration';
import {ReadingText,overlayColors} from '../components/ReadingText';
import {colors,fonts,ui,themed,readingIsDark,readingInk} from '../design';
import {useApp,dailyLesson,createId,dateKey} from '../state/AppProvider';
import {longLevel,LONG_LEVELS,readingRejection,repeatFactor,xpFor,passed,pickPassage,lessonFeedback,effectiveWpm,MEASURED_EXERCISES,COMPREHENSION_GATE,BASELINE_MIN,baselineAccepted,shuffleQuestions,pathProgress,adjustTempo,tempoNote} from '../state/rules';
import {nextDailyStep,phraseLength} from '../components/trainingModel';
import {reachedParagraph,bookProgress} from '../state/books';
import {lessonForDay} from '../data/lessons';
import {DayComplete} from '../components/DayComplete';
import {feel} from '../state/feedback';
import {getExercise,PASSAGES,CHILD_PASSAGES,LONG_PASSAGES,TEST_PASSAGES,WORD_GAME_ITEMS,WORD_LEVELS,wordLevelSpec,wordsForLevel} from '../data/content';
import {tipForExercise} from '../data/tips';
import type {TrainingRequest,SessionResult,Passage} from '../types';
import {readingBackground} from './LibraryScreens';
type Phase='intro'|'reading'|'quiz'|'result';
const games=['peripheral','groups','wordflash','catcher'];
const paced=['rsvp','chunks','forward','fixation','sprint','flow'];
const rests=['rhythm','relax','eye'];
function shuffle<T>(input:T[]){const a=[...input];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function TrainingScreen({request,onClose,onProfile,onDaily}:{request:TrainingRequest;onClose:()=>void;onProfile?:()=>void;onDaily?:()=>void}){
 const app=useApp();const {state,addSession,setBaseline,setTargetWpm,setBookPosition}=app;const [daily]=useState(()=>dailyLesson(state));const plan=daily.plan,steps=plan.length;const [dailyStep,setDailyStep]=useState(()=>request.daily?nextDailyStep(plan,state.sessions,dateKey()):0);const exercise=getExercise(request.daily?plan[Math.min(dailyStep,steps-1)].id:request.exerciseId);
 const dayLesson=request.daily?daily.lesson:null;const lesson=dayLesson&&dailyStep===0?dayLesson:null;const tempoTouched=useRef(false);
 const [phase,setPhase]=useState<Phase>('intro');const [paused,setPaused]=useState(false);const [readProgress,setReadProgress]=useState(0);const scrollBox=useRef({y:0,view:1,content:1});const measureRead=(patch:Partial<{y:number;view:number;content:number}>)=>{Object.assign(scrollBox.current,patch);const b=scrollBox.current;setReadProgress(b.content>0?Math.min(1,(b.y+b.view)/b.content):0);};const [confirmExit,setConfirmExit]=useState(false);const [info,setInfo]=useState(false);const [tempo,setTempo]=useState(state.targetWpm);const [cursor,setCursor]=useState(0);const [seconds,setSeconds]=useState(0);const [answers,setAnswers]=useState<Record<number,number>>({});const [questionIndex,setQuestionIndex]=useState(0);const [result,setResult]=useState<SessionResult|null>(null);const [full,setFull]=useState(false);const [message,setMessage]=useState('');const [tempoMsg,setTempoMsg]=useState<string|null>(null);const [round,setRound]=useState(0);const [score,setScore]=useState(0);const [revealed,setRevealed]=useState(true);const [roundFeedback,setRoundFeedback]=useState<string|null>(null);const [line,setLine]=useState(0);const [reduceMotion,setReduceMotion]=useState(false);const [picked,setPicked]=useState<number|null>(null);const [animatedWpm,setAnimatedWpm]=useState(0);const [controlsVisible,setControlsVisible]=useState(true);const sessionTip=useMemo(()=>tipForExercise(exercise.id,state.sessions.length),[exercise.id,state.sessions.length]);const [guideAuto,setGuideAuto]=useState(false);const [guideSpeed,setGuideSpeed]=useState(12);const [eyeMode,setEyeMode]=useState<EyeMode>('lr');const [eyeSpeed,setEyeSpeed]=useState(3);const [eyeSeconds,setEyeSeconds]=useState(60);const [chunkSize,setChunkSize]=useState(3);const [wordLevel,setWordLevel]=useState(2);const [spread,setSpread]=useState(60);const [flashMs,setFlashMs]=useState(400);const [bestSpread,setBestSpread]=useState(0);const [anchor,setAnchor]=useState(false);const [record,setRecord]=useState(false);const [variant,setVariant]=useState('');const [skipped,setSkipped]=useState<string[]>([]);const [pendingBaseline,setPendingBaseline]=useState<{wpm:number;comprehension:number}|null>(null);const baselineTries=useRef(0);const [probe,setProbe]=useState(false);const [tune,setTune]=useState(false);const [probes,setProbes]=useState({asked:0,wandered:0});const [previewStep,setPreviewStep]=useState(1);const [repeated,setRepeated]=useState(false);
 const activeMs=useRef(0);const lastTick=useRef(0);const saved=useRef(false);const currentRunId=useRef(createId());const timeout=useRef<ReturnType<typeof setTimeout>|null>(null);const controlTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const [passageSeed,setPassageSeed]=useState(state.sessions.length);const sessionsAtStart=useMemo(()=>state.sessions,[passageSeed]);
 const level=useMemo(()=>longLevel(state.sessions,id=>LONG_PASSAGES.find(p=>p.id===id)?.level),[passageSeed]);
 const ownText=lesson?.params.ownText&&state.texts.length?state.texts[state.texts.length-1]:null;const custom=request.text||ownText;
 const passage=useMemo<Passage>(()=>{if(custom)return {id:custom.id,title:custom.title,text:custom.text,questions:custom.questions||[]};const pool=state.kidsMode||exercise.mode==='sprint'?CHILD_PASSAGES:exercise.id==='long'?LONG_PASSAGES.filter(p=>p.level===level):exercise.id==='baseline'||exercise.id==='retest'?TEST_PASSAGES:PASSAGES;return shuffleQuestions(pickPassage(pool,sessionsAtStart,passageSeed,skipped));},[custom,passageSeed,sessionsAtStart,state.kidsMode,exercise.id,level,skipped]);
 const words=useMemo(()=>passage.text.trim().split(/\s+/).filter(Boolean),[passage]);const paragraphs=useMemo(()=>passage.text.split(/\n\n/).filter(Boolean),[passage]);const paperLines=useMemo(()=>{const out=[];for(let i=0;i<words.length;i+=12)out.push(words.slice(i,i+12).join(' '));return out;},[words]);const isPaced=paced.includes(exercise.mode)||(exercise.mode==='innerstem'&&variant==='metronoom'),isGame=games.includes(exercise.mode),isRest=rests.includes(exercise.mode);const restLimit=exercise.mode==='eye'?eyeSeconds:60;const measuredMode=exercise.mode==='reading'||exercise.mode==='paper'||(exercise.mode==='innerstem'&&variant==='kernwoorden')||(exercise.mode==='skim'&&variant==='previewing');const timedLimit=exercise.mode==='skim'?30:0;const firstSentence=(p:string)=>p.match(/^[\s\S]*?[.!?](\s|$)/)?.[0]?.trim()||p;const chunk=isPaced?chunkSize:1;const step=exercise.mode==='chunks'||exercise.mode==='flow'?phraseLength(words,cursor,exercise.mode==='flow'?3:chunk):Math.min(chunk,Math.max(1,words.length-cursor));const chunkRange=['chunks','fixation','forward'].includes(exercise.mode)?{min:2,max:7}:{min:1,max:5};
 const gameItems=useMemo(()=>{const pool=exercise.mode==='wordflash'?wordsForLevel(wordLevel):WORD_GAME_ITEMS;const out=[];while(out.length<10)out.push(...shuffle(pool));return out.slice(0,10);},[passageSeed,wordLevel,exercise.mode]);const item=gameItems[Math.min(round,9)];
 const targetPair=useMemo(()=>{const a=gameItems[Math.min(round,9)].word;const b=gameItems[(round+3)%10].word;return `${a} · ${b}`;},[gameItems,round]);
 const correctOption=isGame&&(exercise.mode==='groups'||exercise.mode==='peripheral')?targetPair:item.word;
 const options=useMemo(()=>shuffle((exercise.mode==='peripheral'||exercise.mode==='groups')?[targetPair,`${item.word} · ${gameItems[(round+5)%10].word}`,`${gameItems[(round+2)%10].word} · ${item.word}`,`${gameItems[(round+1)%10].word} · ${gameItems[(round+6)%10].word}`]:[item.word,...item.distractors.slice(0,3)]),[round,gameItems,targetPair,exercise.mode]);
 const scanTargets=useMemo(()=>shuffle([...new Set(words.map(w=>w.replace(/[^\p{L}]/gu,'')).filter(w=>w.length>5))]).slice(0,5),[words]);const scanTarget=scanTargets[Math.min(round,scanTargets.length-1)];
 const bg=readingBackground(state.settings),dark=readingIsDark(state.settings);const wide=useWindowDimensions().width>=760;
 useEffect(()=>{AccessibilityInfo.isReduceMotionEnabled().then(setReduceMotion);const sub=AccessibilityInfo.addEventListener('reduceMotionChanged',setReduceMotion);return()=>sub.remove();},[]);
 useEffect(()=>{const sub=NativeAppState.addEventListener('change',s=>{if(s!=='active')setPaused(true);});const hide=()=>{if(typeof document!=='undefined'&&document.hidden)setPaused(true);};if(typeof document!=='undefined')document.addEventListener('visibilitychange',hide);return()=>{sub.remove();if(typeof document!=='undefined')document.removeEventListener('visibilitychange',hide);};},[]);
 useEffect(()=>{if(phase!=='reading'||paused)return;lastTick.current=Date.now();const id=setInterval(()=>{const now=Date.now();activeMs.current+=Math.min(now-lastTick.current,500);lastTick.current=now;setSeconds(activeMs.current/1000);},100);return()=>{clearInterval(id);activeMs.current+=Math.min(Math.max(0,Date.now()-lastTick.current),500);};},[phase,paused]);
 useEffect(()=>{if(phase!=='reading'||paused||!isPaced)return;const id=setTimeout(()=>{const next=cursor+step;if(next>=words.length){setCursor(words.length);finishReading(true);}else setCursor(next);},60000/tempo*Math.max(1,step));return()=>clearTimeout(id);},[phase,paused,cursor,tempo,exercise.id]);
 useEffect(()=>{if(phase!=='reading'||paused||exercise.mode!=='paper'||!guideAuto)return;const id=setTimeout(()=>{if(line>=paperLines.length-1)finishReading(true);else setLine(line+1);},guideSpeed*100);return()=>clearTimeout(id);},[phase,paused,exercise.mode,guideAuto,guideSpeed,line,paperLines.length]);
 useEffect(()=>{if(phase==='reading'&&!paused&&isRest&&seconds>=restLimit)saveResult(null,true,0);},[seconds,phase,paused,restLimit]);
 useEffect(()=>{if(phase!=='reading'||paused||!timedLimit||seconds<timedLimit)return;if(exercise.mode==='skim'&&variant==='previewing'){if(previewStep===1){setPreviewStep(2);activeMs.current=0;setSeconds(0);}return;}finishReading(true);},[seconds,phase,paused,timedLimit,variant,previewStep]);
 useEffect(()=>{if(phase!=='reading'||!isGame||paused||roundFeedback||exercise.mode==='peripheral')return;setRevealed(true);if(exercise.mode==='catcher')return;const id=setTimeout(()=>setRevealed(false),exercise.mode==='wordflash'?wordLevelSpec(wordLevel).flashMs:state.kidsMode?1800:1400);return()=>clearTimeout(id);},[round,phase,paused,exercise.mode,roundFeedback,wordLevel]);
 useEffect(()=>{if(phase!=='reading'||exercise.mode!=='peripheral'||paused||roundFeedback)return;setAnchor(true);setRevealed(false);const fixate=setTimeout(()=>setRevealed(true),700);const flash=setTimeout(()=>{setRevealed(false);setAnchor(false);},700+flashMs);return()=>{clearTimeout(fixate);clearTimeout(flash);};},[round,phase,paused,roundFeedback,flashMs,exercise.mode]);
 useEffect(()=>{const p=lesson?.params||{};setChunkSize(p.chunk??(['chunks','fixation','forward'].includes(exercise.mode)?3:1));setTempo(p.tempoFactor?Math.max(60,Math.min(800,Math.round(state.targetWpm*p.tempoFactor/10)*10)):state.targetWpm);if(p.spread)setSpread(p.spread);if(p.flashMs)setFlashMs(p.flashMs);if(p.guideAuto!==undefined)setGuideAuto(p.guideAuto);if(p.eyeMode)setEyeMode(p.eyeMode);setVariant(p.variant??(exercise.mode==='skim'?'skimmen':exercise.mode==='innerstem'?'metronoom':''));tempoTouched.current=false;},[exercise.id,dailyStep]);
 useEffect(()=>()=>{if(timeout.current)clearTimeout(timeout.current);if(controlTimer.current)clearTimeout(controlTimer.current);},[]);
 useEffect(()=>{if(phase!=='result'||!result)return;const goal=result.wpm;if(reduceMotion){setAnimatedWpm(goal);return;}const start=Date.now();const id=setInterval(()=>{const t=Math.min(1,(Date.now()-start)/750);setAnimatedWpm(Math.round(goal*(1-Math.pow(1-t,3))));if(t>=1)clearInterval(id);},25);return()=>clearInterval(id);},[phase,result,reduceMotion]);
 function revealControls(){setControlsVisible(true);if(controlTimer.current)clearTimeout(controlTimer.current);if(!paused)controlTimer.current=setTimeout(()=>setControlsVisible(false),3000);}
 function start(){setProbes({asked:0,wandered:0});setProbe(false);setPreviewStep(1);setPhase('reading');setPaused(false);setCursor(0);setLine(0);setSeconds(0);setAnswers({});setQuestionIndex(0);setRound(0);setScore(0);setResult(null);setMessage('');setFull(false);saved.current=false;activeMs.current=0;currentRunId.current=createId();revealControls();}
 function finishReading(complete:boolean){if(saved.current)return;const dur=activeMs.current/1000;if(dur<3){setMessage('Neem rustig de tijd om de tekst te lezen.');return;}const rejected=complete&&measuredMode&&exercise.mode!=='paper'?readingRejection(words.length,dur,state.kidsMode):null;if(rejected){setMessage(rejected);return;}setFull(complete);setPaused(false);if(complete&&passage.questions.length&&exercise.mode!=='scan'){setPhase('quiz');setAnswers({});setQuestionIndex(0);}else saveResult(null,complete,isPaced?Math.min(words.length,cursor):words.length);}
 function saveResult(comprehension:number|null,complete:boolean,readWords?:number,recognitionScore?:number){if(saved.current)return;const dur=Math.max(.1,activeMs.current/1000);let read=readWords??(complete?words.length:cursor);const measured=measuredMode;const wpm=isRest||isGame||exercise.mode==='scan'||(!measured&&!isPaced)?0:measured?Math.round(read/dur*60):tempo;
 if(!isRest&&!isGame&&exercise.mode!=='scan'&&(read<10||dur<3)){setMessage('Lees minstens 10 woorden voordat je deze oefening afrondt.');return;}
 saved.current=true;setFull(complete);const passageId=isGame||isRest?undefined:passage.id;const repeat=repeatFactor(state.sessions,passageId);const ok=passed(complete,comprehension);
 const best=Math.max(0,...state.sessions.filter(x=>MEASURED_EXERCISES.includes(x.exerciseId)&&x.comprehension!==null&&x.comprehension>=COMPREHENSION_GATE).map(x=>x.wpm));setRecord(measured&&ok&&best>0&&wpm>best);setRepeated(repeat<1);
 const r:SessionResult={id:currentRunId.current,exerciseId:exercise.id,skill:exercise.skill,wpm,comprehension,words:Math.max(0,read),durationSeconds:dur,date:new Date().toISOString(),xp:xpFor({complete,comprehension,repeat}),...(passageId?{passageId}:{}),...(ok&&(request.daily||request.baseline)?{dailyId:dateKey()}:{}),...(ok&&lesson?{lessonDay:daily.day}:{}),...(probes.asked?{probes:probes.asked,wandered:probes.wandered}:{})};
 if((request.baseline||exercise.id==='baseline')&&!state.baseline){if(comprehension!==null){baselineTries.current+=1;if(baselineAccepted(comprehension,baselineTries.current))setBaseline({wpm,comprehension});else setPendingBaseline({wpm,comprehension});}}else if(isPaced&&tempoTouched.current)setTargetWpm(tempo);
 if(request.book){const reached=reachedParagraph(request.book,read,complete);if(reached.para>request.book.from)setBookPosition(request.book.id,reached.para,request.book.startWords+reached.words);}
 if(!request.baseline&&exercise.id!=='baseline'&&!(isPaced&&tempoTouched.current)){const adj=adjustTempo(state,r.comprehension,r.probes?{asked:r.probes,wandered:r.wandered??0}:undefined);setTempoMsg(tempoNote(adj.reason,state.targetWpm,adj.targetWpm));}else setTempoMsg(null);addSession(r);setResult(r);setPhase('result');setPaused(false);if(recognitionScore!==undefined)setScore(recognitionScore);
 }
 function submitAnswer(value:number){const next={...answers,[questionIndex]:value};setAnswers(next);if(questionIndex+1<passage.questions.length)setQuestionIndex(questionIndex+1);else{const correct=passage.questions.reduce((n,q,i)=>n+(next[i]===q.answer?1:0),0);saveResult(Math.round(correct/passage.questions.length*100),true,words.length);}}
 function gameAnswer(option:string){if(roundFeedback||paused)return;const correct=option===correctOption;const nextScore=score+(correct?1:0);setScore(nextScore);if(exercise.mode==='peripheral'){if(correct)setBestSpread(b=>Math.max(b,spread));setSpread(v=>Math.max(20,Math.min(95,v+(correct?5:-5))));}setRoundFeedback(correct?'Goed gezien.':`Het was: ${correctOption}`);timeout.current=setTimeout(()=>{setRoundFeedback(null);if(round>=9)saveResult(null,true,10,nextScore);else setRound(round+1);},900);}
 function scanAnswer(word:string){if(paused)return;if(word.replace(/[^\p{L}]/gu,'')===scanTarget){if(round+1>=scanTargets.length)saveResult(null,true,scanTargets.length);else setRound(round+1);setMessage('');}else setMessage('Bijna. Zoek het woord '+scanTarget+'.');}
 /** Bij lange teksten en boeken vragen we af en toe of je er nog bij was. Afdwalen merken is de eerste stap om het minder te doen. */
 const probeOn=!!request.book||exercise.id==='long';
 useEffect(()=>{if(phase==='result'&&result&&passed(full,result.comprehension))feel.done();},[phase]);
 useEffect(()=>{if(!probeOn||phase!=='reading'||paused||probe)return;if(Math.floor(seconds/PROBE_SECONDS)>probes.asked){setProbe(true);setPaused(true);}},[seconds,phase,paused,probe,probes.asked,probeOn]);
 function answerProbe(wandered:boolean){setProbes(p=>({asked:p.asked+1,wandered:p.wandered+(wandered?1:0)}));setProbe(false);setPaused(false);}
 /** Wissel naar een andere tekst: deze ronde telt niet mee en begint opnieuw. */
 function otherText(restart:boolean){setSkipped(s=>[...s,passage.id]);if(restart)start();}
 const canSwap=!custom&&!isRest&&!isGame;
 function retry(){setPhase('intro');setPassageSeed(passageSeed+1);setResult(null);saved.current=false;setMessage('');}
 function next(){setDailyStep(dailyStep+1);setPhase('intro');setPassageSeed(passageSeed+1);setResult(null);saved.current=false;setMessage('');}
 function quit(){if(phase==='reading'||phase==='quiz'){setPaused(true);setConfirmExit(true);}else onClose();}
 const sessionLabel=request.daily?`${dayLesson?`DAG ${daily.day} · `:'DAGTRAINING · '}${Math.min(dailyStep+1,steps)} VAN ${steps}`:request.baseline?'JOUW VERTREKPUNT':'EEN MOMENT VOOR JEZELF';
 if(request.daily&&dailyStep>=steps)return <DayComplete day={daily.day} lesson={dayLesson} lessonDone={!!dayLesson&&pathProgress(state.sessions).completed.includes(daily.day)} sessions={state.sessions} streak={app.stats.streak} onClose={onClose}/>;
 if(phase==='intro')return <Screen style={{maxWidth:680}} footer={<><Button title={request.baseline?'Start mijn begintest':'Ik ben er klaar voor'} icon="play" onPress={start}/><T variant="caption" style={{textAlign:'center'}}>Je kunt op ieder moment pauzeren.</T></>}><BackHeader title={request.daily?'Jouw dagtraining':lesson?exercise.title:''} onBack={onClose}/>{lesson?<View style={{gap:10,paddingTop:6}}><Pill label={sessionLabel}/><T variant="display" style={{fontSize:34,lineHeight:40}}>{lesson.title}</T><Row><Icon name={exercise.icon} size={16} color={colors.accent}/><T variant="label" style={{flex:1}}>{custom?custom.title:exercise.title}</T><T variant="caption">{exercise.minutes} min</T></Row></View>:<View style={{alignItems:'center',gap:21,paddingVertical:20}}><Pill label={sessionLabel}/><Illustration name={exercise.skill==='focus'?'focus':exercise.skill} size={128}/><T variant="display" style={{fontSize:38,lineHeight:43,textAlign:'center'}}>{custom?custom.title:exercise.title}</T><T color={ui.muted} style={{textAlign:'center',maxWidth:460}}>{exercise.description}</T><Row><Pill label={`${exercise.minutes} min`} icon="clock" background={colors.surface} color={ui.muted}/>{exercise.id==='long'&&!custom&&<Pill label={`Niveau ${LONG_LEVELS[level-1]}`} icon="chart" background={colors.surface} color={ui.muted}/>}<Pill label={custom?'Eigen tekst':state.kidsMode?'Kort verhaal':'Op jouw tempo'} icon="leaf" background={colors.surface} color={ui.muted}/></Row></View>}
 {lesson&&<Card style={{backgroundColor:ui.forestSoft,borderWidth:0,gap:12}}><T style={{fontSize:15,lineHeight:23}}>{lesson.what}</T><T color={ui.muted} style={{fontSize:15,lineHeight:23}}>{lesson.why}</T><View style={{height:1,backgroundColor:ui.line}}/><T variant="label">Zo pas je het nu toe</T><T style={{fontSize:15,lineHeight:23}}>{lesson.how}</T>{lesson.params.ownText&&!ownText&&<T variant="caption">Je hebt nog geen eigen tekst bewaard. Je oefent nu met een tekst uit de app; voeg er later een toe via Eigen tekst.</T>}</Card>}
 {request.daily&&dailyStep>0&&<Card style={{backgroundColor:colors.tintLilac,borderWidth:0,gap:10}}><Row><Icon name={dayLesson?'checkcircle':sessionTip.icon} size={18} color={colors.accent}/><T variant="label">{dayLesson?'Pas toe wat je net leerde':'Even tussendoor'}</T></Row><T variant="heading" style={{fontSize:19}}>{dayLesson?dayLesson.title:sessionTip.title}</T><T style={{fontSize:15}}>{dayLesson?dayLesson.hint:sessionTip.body}</T><T variant="caption">Neem dit mee in de oefening hierna.</T></Card>}
 {exercise.mode==='innerstem'&&<Card style={{gap:14,backgroundColor:colors.surface,borderWidth:0}}><Choice label="Zo lees je" value={variant} options={[{value:'metronoom',label:'Metronoom'},{value:'kernwoorden',label:'Kernwoorden'}]} onChange={setVariant}/><T variant="caption">{variant==='metronoom'?'Lees mee op een gelijkmatig ritme, een fractie sneller dan praten. Je binnenstem mag meelopen, als een fluistering. Verhoog pas als je de hoofdgedachte nog kunt navertellen.':'Lees de tekst in je eigen tempo en laat je binnenstem alleen de woorden benadrukken die de betekenis dragen. De kleine woordjes glijden erlangs. Daarna volgen vragen.'}</T><T variant="caption">Je binnenstem helpt je begrijpen. Het doel is een lichtere stem, geen stille.</T></Card>}
 {exercise.mode==='skim'&&<Card style={{gap:14,backgroundColor:colors.surface,borderWidth:0}}><Choice label="Kies je aanpak" value={variant} options={[{value:'skimmen',label:'Skimmen'},{value:'previewing',label:'Previewing'}]} onChange={setVariant}/><T variant="caption">{variant==='skimmen'?'De kernzinnen zijn gemarkeerd. Je hebt 30 seconden om de hoofdgedachte te vangen zonder alles te lezen. Daarna volgen de vragen.':'Stap 1: 30 seconden alleen de titel en de eerste zin van elke alinea. Stap 2: de hele tekst lezen. Daarna volgen de vragen.'}</T></Card>}
 {(isPaced||['paper','eye','wordflash','peripheral'].includes(exercise.mode))&&<Card style={{gap:16,backgroundColor:colors.surface,borderWidth:0}}><Pressable accessibilityRole="button" accessibilityState={{expanded:tune}} accessibilityLabel="Oefening aanpassen" onPress={()=>setTune(!tune)} style={{flexDirection:'row',alignItems:'center',gap:12,minHeight:44}}><Icon name="settings" size={18} color={colors.accent}/><View style={{flex:1}}><T variant="label">Aanpassen</T><T variant="caption">{(isPaced?`${tempo} wpm${exercise.mode!=='innerstem'?` · ${chunkSize} ${exercise.mode==='chunks'?'woorden per groep':chunkSize===1?'woord per keer':'woorden per keer'}`:''}`:exercise.mode==='paper'?(guideAuto?'De gids loopt vanzelf mee':'Je gaat zelf verder'):exercise.mode==='eye'?`${EYE_MODES.find(m=>m.value===eyeMode)?.label??''} · ${eyeSeconds/60} min`:exercise.mode==='peripheral'?`${spread}% breed · ${flashMs} ms`:WORD_LEVELS.find(l=>l.level===wordLevel)?.title??'')}</T></View><Icon name={tune?'minus':'plus'} size={18} color={ui.dim}/></Pressable>{tune&&<View style={{gap:16}}>
 {isPaced&&<View style={{gap:15}}><Row style={{justifyContent:'space-between'}}><T variant="label">Een prettig oefentempo</T><Icon name="zap" size={19} color={colors.accent}/></Row><Row style={{justifyContent:'center',gap:28}}><IconButton name="minus" label="Tempo verlagen" onPress={()=>{tempoTouched.current=true;setTempo(Math.max(60,tempo-20));}}/><View style={{alignItems:'center'}}><T variant="stat">{tempo}</T><T variant="caption">woorden per minuut</T></View><IconButton name="plus" label="Tempo verhogen" onPress={()=>{tempoTouched.current=true;setTempo(Math.min(800,tempo+20));}}/></Row></View>}
 {isPaced&&exercise.mode!=='innerstem'&&exercise.mode!=='flow'&&<View style={{gap:24}}><Stepper label="Woorden per keer" icon="text" value={chunkSize} unit={exercise.mode==='chunks'?'woorden, geknipt per zinsdeel':chunkSize===1?'woord tegelijk':'woorden tegelijk'} min={chunkRange.min} max={chunkRange.max} step={1} onChange={setChunkSize}/></View>}
 {exercise.mode==='paper'&&<View style={{gap:22}}><Choice label="De gids" value={guideAuto?'auto':'zelf'} options={[{value:'zelf',label:'Ik ga zelf verder'},{value:'auto',label:'Loopt vanzelf mee'}]} onChange={v=>setGuideAuto(v==='auto')}/>{guideAuto&&<Stepper label="Tempo van de gids" icon="clock" value={guideSpeed} unit="seconden per regel" min={3} max={30} step={1} onChange={setGuideSpeed} format={v=>(v/10).toFixed(1).replace('.',',')}/>}</View>}
 {exercise.mode==='eye'&&<View style={{gap:22}}><Choice label="Patroon" value={eyeMode} options={EYE_MODES} onChange={setEyeMode}/><Stepper label="Snelheid" icon="zap" value={eyeSpeed} unit="van 10" min={1} max={10} step={1} onChange={setEyeSpeed}/><Choice label="Duur" value={String(eyeSeconds)} options={[{value:'60',label:'1 minuut'},{value:'180',label:'3 minuten'},{value:'360',label:'6 minuten'}]} onChange={v=>setEyeSeconds(Number(v))}/></View>}
 {exercise.mode==='wordflash'&&<View style={{gap:16}}><Choice label="Niveau" value={String(wordLevel)} options={WORD_LEVELS.map(l=>({value:String(l.level),label:l.title}))} onChange={v=>setWordLevel(Number(v))}/><T variant="caption">Langere woorden krijgen een kortere flits.</T></View>}
 {exercise.mode==='peripheral'&&<View style={{gap:24}}><Stepper label="Breedte" icon="eye" value={spread} unit="% van het scherm" min={20} max={95} step={5} onChange={setSpread}/><Stepper label="Flitstijd" value={flashMs} unit="milliseconden" min={120} max={1200} step={40} onChange={setFlashMs}/><T variant="caption">De breedte groeit mee als je goed scoort, en zakt een stapje als het te snel gaat.</T></View>}
 </View>}</Card>}
 {request.daily&&<Card style={{gap:14}}>{plan.map((e,i)=><Row key={i}><View style={{width:30,height:30,borderRadius:15,backgroundColor:i===dailyStep?colors.accent:colors.surface,alignItems:'center',justifyContent:'center'}}>{i<dailyStep?<Icon name="check" size={16} color={colors.accent}/>:<T variant="caption" color={i===dailyStep?colors.bg:ui.muted}>{i+1}</T>}</View><T variant="label" style={{flex:1}}>{e.title}</T><T variant="caption">{e.minutes} min</T></Row>)}</Card>}
 {canSwap&&exercise.mode!=='scan'&&<Row style={{justifyContent:'space-between',paddingHorizontal:4}}><View style={{flex:1}}><T variant="caption">Tekst</T><T variant="label" numberOfLines={1}>{passage.title}</T></View><Pressable accessibilityRole="button" accessibilityLabel="Kies een andere tekst" onPress={()=>otherText(false)} style={{flexDirection:'row',gap:8,alignItems:'center',minHeight:44}}><Icon name="refresh" size={16} color={colors.accent}/><T variant="label" color={colors.accent} style={{fontSize:13}}>Andere tekst</T></Pressable></Row>}</Screen>;
 if(phase==='result'&&result){const ok=passed(full,result.comprehension);const dailyMore=request.daily&&ok&&dailyStep<steps-1;const firstLesson=!!onDaily&&request.baseline&&!request.daily&&ok&&daily.day===1&&!daily.doneToday;const primary=firstLesson?<><Button title="Verder met je eerste les" icon="arrow" onPress={onDaily}/><T variant="caption" style={{textAlign:'center'}}>Nog twee korte oefeningen van een minuut. De begintest telt al mee.</T><Button title="Later" secondary onPress={onClose}/></>:<><Button title={dailyMore?'Verder met mijn volgende oefening':request.daily&&!ok?'Probeer het opnieuw met een nieuwe tekst':request.daily&&dailyStep>=steps-1?'Rond mijn dagsessie af':request.book?'Terug naar je boek':'Terug naar mijn leesplek'} icon="arrow" onPress={()=>dailyMore||(request.daily&&ok&&dailyStep>=steps-1)?next():request.daily&&!ok?retry():onClose()}/>{request.daily&&!ok&&<Button title="Stop voor vandaag" secondary onPress={onClose}/>}</>;return <Screen style={{maxWidth:680}} footer={pendingBaseline?undefined:primary}><View style={{alignItems:'center',gap:16,paddingTop:20}}><Pill label={pendingBaseline?'BIJNA':request.daily?`OEFENING ${dailyStep+1} VAN 3`:'MOOI GEDAAN'} icon={pendingBaseline?'refresh':'check'}/><Illustration name="resultaat-hero" size={145}/>{record&&<Pill label="PERSOONLIJK RECORD" icon="trophy" background={colors.tintSun} color={ui.forestInk}/>}<T variant="title" style={{textAlign:'center'}}>{pendingBaseline?'Nog één keer, rustiger?':request.baseline||exercise.id==='baseline'?'Je vertrekpunt staat.':!full?'Een klein stukje is ook een begin.':!ok?'Nog even oefenen.':'Een moment om trots op te zijn.'}</T><T color={ui.muted} style={{textAlign:'center'}}>{pendingBaseline?`Je begreep ${pendingBaseline.comprehension}% van de tekst. Een vertrekpunt is pas eerlijk als je ook begrijpt wat je leest, anders lijk je later niet vooruit te gaan. Lees de volgende tekst op je gewone tempo.`:request.baseline?'Dit is jouw vertrekpunt. Van hieruit gaan we rustig verder.':!full?'Je hebt de oefening eerder afgerond. Je oefentijd is bewaard.':!ok?`Onder ${COMPREHENSION_GATE}% begrip telt een ronde als oefening. Je krijgt oefen-XP, maar de les en je record blijven staan.`:result.comprehension!==null&&result.wpm>0?`Je las ${result.wpm} woorden per minuut en begreep ${result.comprehension}% van de tekst.`:'Je hebt aandacht gegeven aan je leesritme. Dat telt.'}</T></View>
 {probes.asked>0&&<Card style={{gap:8,backgroundColor:ui.subtle,borderWidth:0}}><Row><Icon name="eye" size={18} color={colors.accent}/><T variant="label">{probes.wandered===0?`Je was er ${probes.asked===1?'bij de check':`alle ${probes.asked} keer`} bij.`:`Je dwaalde ${probes.wandered} van de ${probes.asked} keer af.`}</T></Row><T variant="caption">{probes.wandered===0?'Mooi. Blijf merken wanneer je aandacht wegzakt, zeker bij een lange tekst.':'Dat is heel gewoon. Merk je het tijdens het lezen? Ga dan terug naar het begin van de alinea en lees rustig door.'}</T></Card>}
 {pendingBaseline&&<Card style={{gap:12,backgroundColor:ui.forestSoft,borderWidth:0}}><Button title="Nog een keer, rustiger" icon="refresh" onPress={()=>{setPendingBaseline(null);retry();}}/><Button title="Toch als vertrekpunt gebruiken" secondary onPress={()=>{setBaseline(pendingBaseline);setPendingBaseline(null);}}/><T variant="caption">Vanaf {BASELINE_MIN}% begrip telt je begintest meteen. De tweede keer telt hij altijd.</T></Card>}
 <Card style={{backgroundColor:colors.surface,borderWidth:0,alignItems:'center',gap:5,padding:28}}><T variant="display" style={{fontSize:68,lineHeight:76}}>{result.wpm?animatedWpm:isGame?`${score}/10`:exercise.mode==='scan'?scanTargets.length:Math.round(result.durationSeconds)}</T><T variant="caption">{result.wpm?(measuredMode?'woorden per minuut · gemeten':'woorden per minuut · oefentempo'):isGame?(exercise.mode==='peripheral'?`woorden herkend · tot ${bestSpread||spread}% breedte`:'woorden of woordgroepen herkend'):exercise.mode==='scan'?'zoekwoorden gevonden':isRest?'seconden rust en aandacht':'seconden gelezen'}</T></Card><Row style={{gap:14}}><Card style={{flex:1,alignItems:'center',gap:5,backgroundColor:ui.subtle,borderWidth:0}}><T variant="stat">{result.comprehension===null?'—':`${result.comprehension}%`}</T><T variant="caption">{result.comprehension===null?'begrip niet gemeten':'tekstbegrip'}</T></Card><Card style={{flex:1,alignItems:'center',gap:5,backgroundColor:ui.subtle,borderWidth:0}}><T variant="stat">+{result.xp}</T><T variant="caption">{repeated?'lees-XP · deze tekst las je vandaag al':'lees-XP'}</T></Card></Row>
 {lesson&&<Card style={{backgroundColor:ui.forestSoft,borderWidth:0,gap:10}}><Row><Icon name="sparkles" size={18} color={colors.accent}/><T variant="label">{`Dag ${daily.day} · ${lesson.title}`}</T></Row><T style={{fontSize:15,lineHeight:23}}>{lessonFeedback(lesson,{wpm:result.wpm,comprehension:result.comprehension,score:isGame?score:undefined,baselineEffective:state.baseline&&exercise.id!=='baseline'?effectiveWpm(state.baseline.wpm,state.baseline.comprehension):undefined})}</T></Card>}
 <Card style={{backgroundColor:colors.tintLilac,borderWidth:0,gap:10}}><Row><Icon name={sessionTip.icon} size={18} color={colors.accent}/><T variant="label">{sessionTip.title}</T></Row><T style={{fontSize:15}}>{sessionTip.body}</T>{tempoMsg?<Row style={{alignItems:'flex-start'}}><Icon name="zap" size={16} color={colors.accent}/><T variant="caption" style={{flex:1}}>{tempoMsg}</T></Row>:result.comprehension!==null&&<T variant="caption">{result.comprehension>=80?'Je nam de inhoud goed mee. Blijf dit tempo volgen zolang het prettig voelt.':'Begrip en tempo zoeken nog hun balans. Dat hoort erbij.'}</T>}</Card>
 {request.book&&(()=>{const b=state.books.find(x=>x.id===request.book!.id);return b?<Card style={{gap:10,backgroundColor:ui.forestSoft,borderWidth:0}}><Row style={{justifyContent:'space-between'}}><T variant="label" numberOfLines={1} style={{flex:1}}>{b.title}</T><T variant="label" color={colors.accent}>{Math.round(bookProgress(b)*100)}%</T></Row><ProgressBar value={bookProgress(b)}/><T variant="caption">Je bladwijzer staat waar je gebleven bent.</T></Card>:null;})()}
 {result.comprehension!==null&&passage.questions.some((q,i)=>answers[i]!==q.answer)&&<Card style={{gap:12}}><T variant="label">Even terug naar de inhoud</T>{passage.questions.map((q,i)=>answers[i]!==q.answer?<View key={i} style={{gap:4}}><T variant="caption">{q.question}</T><T variant="label" style={{fontSize:14}}>{q.options[q.answer]}</T></View>:null)}</Card>}
 {!state.profile.name&&onProfile&&!dailyMore&&<Button title="Maak mijn leesplek persoonlijk" secondary onPress={onProfile}/>}</Screen>;}
 if(phase==='quiz'){const q=passage.questions[questionIndex];return <Screen style={{maxWidth:680}}><Row><IconButton name="close" label="Stoppen met deze oefening" onPress={quit}/><View style={{flex:1,gap:8,marginLeft:6}}><Row style={{justifyContent:'space-between'}}><T variant="eyebrow">WAT IS JE BIJGEBLEVEN?</T><T variant="caption">{questionIndex+1} van {passage.questions.length}</T></Row><ProgressBar value={(questionIndex+1)/passage.questions.length}/></View></Row><T variant="title" style={{fontSize:25,lineHeight:32}} accessibilityRole="header">{q.question}</T><View style={{gap:11}}>{q.options.map((o,i)=><Card key={i} onPress={()=>{if(picked!==null)return;setPicked(i);feel.tap();setTimeout(()=>{setPicked(null);submitAnswer(i);},reduceMotion?0:240);}} accessibilityLabel={`${String.fromCharCode(65+i)}: ${o}`} style={{flexDirection:'row',alignItems:'center',gap:14,minHeight:64,paddingVertical:14,...(picked===i?{borderColor:colors.accent,borderWidth:2,backgroundColor:ui.forestSoft}:null)}}><View style={s.optionCircle}><T variant="label" color={colors.accent}>{String.fromCharCode(65+i)}</T></View><T style={{flex:1}}>{o}</T><Icon name={picked===i?'check':'chevron'} size={17} color={picked===i?colors.accent:ui.dim}/></Card>)}</View>{confirmExit&&<ExitConfirm onCancel={()=>{setConfirmExit(false);setPaused(false);}} onExit={onClose}/>}</Screen>;}
 const freeReading=!isPaced&&!isRest&&!isGame&&exercise.mode!=='scan'&&exercise.mode!=='paper'&&!(exercise.mode==='skim'&&variant==='previewing'&&previewStep===1); const progress=isPaced?cursor/words.length:isRest?seconds/60:isGame?round/10:exercise.mode==='scan'?round/scanTargets.length:exercise.mode==='paper'?(line+1)/paperLines.length:0;
 return <View style={{flex:1,backgroundColor:bg}}><View style={{width:'100%',maxWidth:940,alignSelf:'center',flex:1,paddingHorizontal:wide?30:22,paddingTop:18,paddingBottom:18}}><Row style={{marginBottom:14}}><IconButton name="close" label="Oefening sluiten" onPress={quit}/><View style={{flex:1,alignItems:'center',gap:2}}><T variant="label" color={readingInk(state.settings)}>{exercise.title}</T><T variant="caption">{request.daily?`${dailyStep+1} van ${steps} · `:''}{Math.floor(seconds/60)}:{String(Math.floor(seconds%60)).padStart(2,'0')}</T></View><IconButton name="info" label="Uitleg over deze oefening" onPress={()=>{setPaused(true);setInfo(true);}}/></Row>
 {isPaced?<Pressable accessibilityLabel="Toon leesbediening" onPress={revealControls} style={{flex:1,justifyContent:exercise.mode==='flow'?'flex-start':'center',alignItems:'center',gap:28,minHeight:250,overflow:'hidden',paddingTop:exercise.mode==='flow'?12:0}}><PacedReadingStage mode={exercise.mode==='innerstem'?'forward':exercise.mode} words={words} cursor={cursor} chunk={step} settings={state.settings} wide={wide}/>{exercise.mode!=='flow'&&<T variant="caption" style={{marginTop:32}}>{paused?'Even op adem komen.':`woord ${Math.min(cursor+1,words.length)} van ${words.length}`}</T>}</Pressable>:
 isRest?<View style={{flex:1,justifyContent:'center',alignItems:'center',gap:28,minHeight:340}}>{exercise.mode==='eye'?<EyeStage mode={eyeMode} speed={eyeSpeed} paused={paused} reduceMotion={reduceMotion}/>:<View style={{width:220,height:220,borderRadius:110,backgroundColor:ui.forestSoft,alignItems:'center',justifyContent:'center',transform:[{scale:reduceMotion?1:.9+Math.sin(seconds*Math.PI/4)*.08}]}}><View style={{width:160,height:160,borderRadius:80,backgroundColor:'#C8DDCC',alignItems:'center',justifyContent:'center'}}><Icon name={exercise.mode==='relax'?'leaf':'heart'} size={45} color={colors.accent}/></View></View>}<T variant="heading" color={readingInk(state.settings)}>{exercise.mode==='relax'?'Kijk even in de verte.':exercise.mode==='eye'?'Volg rustig het puntje.':seconds%8<4?'Adem rustig in.':'Adem rustig uit.'}</T><T variant="caption">{Math.max(0,restLimit-Math.floor(seconds))} seconden voor jezelf</T></View>:
 isGame?<View style={{flex:1,justifyContent:'center',gap:25,paddingVertical:20}}><T variant="eyebrow" style={{textAlign:'center'}}>RONDE {round+1} VAN 10</T>{roundFeedback?<View style={{minHeight:250,alignItems:'center',justifyContent:'center',gap:18}}><Icon name={roundFeedback==='Goed gezien.'?'checkcircle':'eye'} color={colors.accent} size={48}/><T variant="heading" style={{textAlign:'center'}}>{roundFeedback}</T></View>:exercise.mode==='peripheral'&&anchor?<View style={{minHeight:250,justifyContent:'center',alignItems:'center',gap:8}}><T variant="caption">Houd je blik op het stipje.</T><PeripheralStage left={item.word} right={gameItems[(round+3)%10].word} spread={spread} visible={revealed} dark={dark}/></View>:revealed&&exercise.mode!=='catcher'?<View style={{minHeight:250,justifyContent:'center',alignItems:'center',gap:20}}><T variant="caption">{exercise.mode==='peripheral'?'Houd je blik in het midden.':'Kijk rustig naar de woorden.'}</T><T variant="heading" style={{fontSize:exercise.mode==='peripheral'?25:32,textAlign:'center',letterSpacing:exercise.mode==='peripheral'?3:0}}>{exercise.mode==='peripheral'?`${item.word}    •    ${gameItems[(round+3)%10].word}`:exercise.mode==='groups'?targetPair:item.word}</T></View>:<><T variant="heading" style={{textAlign:'center'}}>{exercise.mode==='catcher'?`Vind het woord: ${item.word}`:'Wat zag je net?'}</T><View style={{gap:12}}>{options.map((o,i)=><Button key={i} title={o} secondary onPress={()=>gameAnswer(o)} disabled={paused}/>)}</View></>}</View>:
 exercise.mode==='scan'?<View style={{flex:1,gap:20}}><Pill label={`ZOEK: ${scanTarget}`} icon="search"/><ScrollView><View style={{flexDirection:'row',flexWrap:'wrap',gap:4}}>{words.map((w,i)=><Pressable key={i} onPress={()=>scanAnswer(w)} accessibilityRole="button" accessibilityLabel={`Kies ${w}`} style={{paddingHorizontal:4,paddingVertical:9,minHeight:44}}><T style={{fontSize:18}}>{w}</T></Pressable>)}</View></ScrollView></View>:
 exercise.mode==='paper'?<View style={{flex:1,gap:18}}><T variant="heading">{passage.title}</T><ScrollView><View style={{gap:16}}>{paperLines.map((p,i)=><View key={i} style={{padding:14,borderRadius:12,backgroundColor:i===line?ui.forestSoft:'transparent',opacity:i<line?.4:1}}><ReadingText text={p} settings={state.settings}/></View>)}</View></ScrollView><Button title={guideAuto?'Klaar met lezen':line===paperLines.length-1?'Laatste regel gelezen':'Volgende regel'} secondary onPress={()=>guideAuto||line===paperLines.length-1?finishReading(true):setLine(line+1)} disabled={paused}/></View>:
 <ScrollView style={{flex:1}} contentContainerStyle={{paddingVertical:24,paddingHorizontal:wide?50:2,gap:22}} scrollEventThrottle={120} onScroll={e=>measureRead({y:e.nativeEvent.contentOffset.y})} onLayout={e=>measureRead({view:e.nativeEvent.layout.height})} onContentSizeChange={(_,h)=>measureRead({content:h})}>{exercise.mode==='innerstem'&&<Row style={{justifyContent:'center',gap:14}}><Pill label="LEG DE NADRUK OP DE KERNWOORDEN" icon="volume"/></Row>}{exercise.mode==='skim'&&<Pill label={variant==='skimmen'?`HOOFDGEDACHTE · NOG ${Math.max(0,30-Math.floor(seconds))} SEC`:previewStep===1?`STAP 1 · VERKEN DE OPBOUW · NOG ${Math.max(0,30-Math.floor(seconds))} SEC`:'STAP 2 · LEES DE HELE TEKST'} icon="clock"/>}<T variant="heading" color={readingInk(state.settings)}>{passage.title}</T>{exercise.mode==='skim'&&(variant==='skimmen'||previewStep===1)?paragraphs.map((p,i)=>{const first=firstSentence(p);return <View key={i} style={{gap:4}}><ReadingText text={first} settings={state.settings} style={{fontFamily:fonts.strong,color:dark?colors.sage:colors.accent}}/>{variant==='skimmen'&&p.length>first.length&&<ReadingText text={p.slice(first.length).trim()} settings={state.settings} style={{opacity:.55}}/>}</View>;}):paragraphs.map((p,i)=><Pressable key={i} onPress={()=>state.settings.lineGuide&&setLine(i)} style={{padding:state.settings.enabled&&state.settings.lineGuide?12:0,borderRadius:14,backgroundColor:state.settings.enabled&&state.settings.lineGuide&&i===line?ui.forestSoft:'transparent',opacity:state.settings.enabled&&state.settings.lineGuide&&i!==line?.45:1}}><ReadingText text={p} settings={state.settings}/></Pressable>)}</ScrollView>}
 {dayLesson&&!message&&<T variant="caption" style={{textAlign:'center',paddingTop:10}}>{dayLesson.hint}</T>}{!!message&&<T variant="caption" color={ui.error} accessibilityRole="alert" style={{padding:12,textAlign:'center'}}>{message}</T>}
 {freeReading?<View style={{gap:14,paddingTop:14}}><ProgressBar value={readProgress}/><Row style={{gap:12}}><IconButton name={paused?'play':'pause'} label={paused?'Verder lezen':'Pauzeren'} onPress={()=>{setPaused(!paused);setControlsVisible(true);}} style={{backgroundColor:ui.forestSoft}}/><Button title={exercise.mode==='skim'&&variant==='skimmen'?'Ik heb de hoofdgedachte':'Klaar met lezen'} icon="check" onPress={()=>finishReading(true)} disabled={paused} style={{flex:1}}/>{canSwap&&<IconButton name="refresh" label="Oefen met een andere tekst" onPress={()=>otherText(true)}/>}</Row></View>:<View style={{gap:16,paddingTop:18,opacity:isPaced&&!controlsVisible&&!paused?.45:1}}><ProgressBar value={progress}/>{canSwap&&<Pressable accessibilityRole="button" accessibilityLabel="Oefen met een andere tekst" onPress={()=>otherText(true)} style={{alignSelf:'center',flexDirection:'row',gap:8,alignItems:'center',minHeight:44,paddingHorizontal:12}}><Icon name="refresh" size={16} color={colors.accent}/><T variant="label" color={colors.accent} style={{fontSize:13}}>Andere tekst</T></Pressable>}<Row style={{justifyContent:'center',gap:26}}>{isPaced&&<IconButton name="minus" label="Langzamer lezen" onPress={()=>{tempoTouched.current=true;setTempo(Math.max(60,tempo-20));revealControls();}}/>}<IconButton name={paused?'play':'pause'} label={paused?'Verder lezen':'Pauzeren'} onPress={()=>{setPaused(!paused);setControlsVisible(true);}} style={{width:54,height:54,borderRadius:27,backgroundColor:ui.forestSoft}}/>{isPaced&&<IconButton name="plus" label="Sneller lezen" onPress={()=>{tempoTouched.current=true;setTempo(Math.min(800,tempo+20));revealControls();}}/>}{isPaced&&<View><T variant="stat" style={{fontSize:26}}>{tempo}</T><T variant="caption">wpm</T></View>}</Row>{exercise.mode==='skim'&&variant==='previewing'&&previewStep===1?<Button title="Nu de volledige tekst lezen" secondary icon="arrow" onPress={()=>{setPreviewStep(2);activeMs.current=0;setSeconds(0);}} disabled={paused}/>:!isRest&&!isGame&&exercise.mode!=='scan'&&exercise.mode!=='paper'&&<Button title={isPaced?'Eerder afronden':exercise.mode==='skim'&&variant==='skimmen'?'Ik heb de hoofdgedachte':'Klaar met lezen'} secondary onPress={()=>finishReading(!isPaced)} disabled={paused}/>}</View>}
 </View>{state.settings.enabled&&state.settings.overlay!=='none'&&<View pointerEvents="none" style={[StyleSheet.absoluteFill,{backgroundColor:overlayColors[state.settings.overlay],opacity:state.settings.overlayOpacity/100}]}/>}
 {paused&&!confirmExit&&!info&&<View style={s.pauseOverlay}><Card style={{gap:20,alignItems:'center',width:'85%',maxWidth:400}}><Icon name="pause" color={colors.accent} size={36}/><T variant="heading">Even pauze.</T><T variant="caption">Je oefentijd staat stil.</T><Button title="Ik ga weer verder" icon="play" onPress={()=>setPaused(false)} style={{alignSelf:'stretch'}}/><Button title="Stoppen met oefenen" secondary onPress={()=>setConfirmExit(true)} style={{alignSelf:'stretch'}}/></Card></View>}
 {info&&<View style={s.pauseOverlay}><Card style={{width:'85%',maxWidth:450,gap:18}}><T variant="heading">{exercise.title}</T><T>{exercise.description}</T><Button title="Verder met oefenen" onPress={()=>{setInfo(false);setPaused(false);}}/></Card></View>}
 {probe&&<MindProbe onAnswer={answerProbe}/>}{confirmExit&&<ExitConfirm onCancel={()=>{setConfirmExit(false);setPaused(false);}} onExit={onClose}/>}
 </View>;
}
const PROBE_SECONDS=75;
function MindProbe({onAnswer}:{onAnswer:(wandered:boolean)=>void}){return <View style={s.pauseOverlay}><Card style={{width:'85%',maxWidth:420,gap:14}}><T variant="eyebrow">EVEN CHECKEN</T><T variant="heading">Was je er nog bij?</T><T color={ui.muted}>Eerlijk antwoorden helpt het meest. Iedereen dwaalt af; het gaat erom dat je het merkt.</T><Button title="Ja, ik las mee" onPress={()=>onAnswer(false)}/><Button title="Ik was even weg" secondary onPress={()=>onAnswer(true)}/></Card></View>;}
function ExitConfirm({onCancel,onExit}:{onCancel:()=>void;onExit:()=>void}){return <View style={s.pauseOverlay}><Card style={{width:'85%',maxWidth:420,gap:18}}><T variant="heading">Voor nu genoeg?</T><T color={ui.muted}>Deze oefening is nog niet afgerond en wordt niet bewaard. Eerder voltooide oefeningen blijven staan.</T><Button title="Verder met oefenen" onPress={onCancel}/><Button title="Stop voor nu" secondary onPress={onExit}/></Card></View>;}
const s=themed(()=>({fixation:{width:24,height:2,borderRadius:2,backgroundColor:'#B9C8BF'},optionCircle:{width:34,height:34,borderRadius:17,backgroundColor:ui.forestSoft,alignItems:'center',justifyContent:'center'},pauseOverlay:{position:'absolute',top:0,right:0,bottom:0,left:0,backgroundColor:'rgba(15,26,20,.28)',justifyContent:'center',alignItems:'center',zIndex:20}}));
