import React,{useEffect,useMemo,useRef,useState} from 'react';
import {View,Pressable,StyleSheet,ScrollView,TextInput,AppState as NativeAppState,AccessibilityInfo,useWindowDimensions} from 'react-native';
import {T,Button,Card,Icon,IconButton,Row,Pill,ProgressBar,Screen,BackHeader,Stepper,Choice,Slider} from '../components/UI';
import {PeripheralStage} from '../components/PeripheralStage';
import {PacedReadingStage} from '../components/PacedReadingStage';
import {EyeStage,EYE_MODES,type EyeMode} from '../components/EyeStage';
import {RelaxStage} from '../components/RelaxStage';
import {Illustration} from '../components/Illustration';
import {ReadingText,overlayColors} from '../components/ReadingText';
import {colors,fonts,ui,themed,readingIsDark,readingInk} from '../design';
import {useApp,dailyLesson,createId,dateKey} from '../state/AppProvider';
import {longLevel,LONG_LEVELS,readingRejection,repeatFactor,xpFor,passed,pickPassage,lessonFeedback,effectiveWpm,MEASURED_EXERCISES,COMPREHENSION_GATE,BASELINE_MIN,baselineAccepted,shuffleQuestions,pathProgress,decideTempo,keepTempo,baselineTarget,tempoNote,clampWpm,pushPlan,PUSH,type TempoDecision} from '../state/rules';
import {nextDailyStep,phraseLength} from '../components/trainingModel';
import {reachedParagraph,bookProgress} from '../state/books';
import {lessonForDay} from '../data/lessons';
import {DayComplete} from '../components/DayComplete';
import {feel} from '../state/feedback';
import {getExercise,LONG_PASSAGES,WORD_GAME_ITEMS,WORD_LEVELS,wordLevelSpec,wordsForLevel,textPool,libraryFor,choosesText,wordCount} from '../data/content';
import {TextPicker,type PickedText} from '../components/TextPicker';
import {autoQuestions} from '../state/questions';
import {isRecord,bonusXp,levelFor} from '../state/progress';
import {challengeOfDay,challengeDone,meetsChallenge} from '../data/challenges';
import {Celebration,type CelebrationSize} from '../components/Celebration';
import {tipForExercise} from '../data/tips';
import type {TrainingRequest,SessionResult,Passage} from '../types';
import {readingBackground} from './LibraryScreens';
type Phase='intro'|'reading'|'recite'|'quiz'|'result';
const games=['peripheral','groups','wordflash','catcher'];
const paced=['rsvp','chunks','forward','fixation','sprint','flow','push'];
/** Woord voor woord blijft één woord per stap; meer woorden tegelijk is een andere oefening (woordgroepen). */
const singleWord=['rsvp','sprint'];
const rests=['rhythm','relax','eye'];
function shuffle<T>(input:T[]){const a=[...input];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function TrainingScreen({request,onClose,onProfile,onDaily}:{request:TrainingRequest;onClose:()=>void;onProfile?:()=>void;onDaily?:()=>void}){
 const app=useApp();const {state,addSession,setBaseline,setBookPosition,updatePrefs}=app;const [daily]=useState(()=>dailyLesson(state,undefined,request.day));const dayKey=request.day?`${dateKey()}#dag${request.day}`:dateKey();const plan=daily.plan,steps=plan.length;const [dailyStep,setDailyStep]=useState(()=>request.daily?nextDailyStep(plan,state.sessions,dayKey):0);const exercise=getExercise(request.daily?plan[Math.min(dailyStep,steps-1)].id:request.exerciseId);
 const dayLesson=request.daily?daily.lesson:null;const lesson=dayLesson&&dailyStep===0?dayLesson:null;const tempoTouched=useRef(false);
 const [phase,setPhase]=useState<Phase>('intro');const [paused,setPaused]=useState(false);const [readProgress,setReadProgress]=useState(0);const scrollBox=useRef({y:0,view:1,content:1});const measureRead=(patch:Partial<{y:number;view:number;content:number}>)=>{Object.assign(scrollBox.current,patch);const b=scrollBox.current;setReadProgress(b.content>0?Math.min(1,(b.y+b.view)/b.content):0);};const [confirmExit,setConfirmExit]=useState(false);const [info,setInfo]=useState(false);const [tempo,setTempo]=useState(state.targetWpm);const [cursor,setCursor]=useState(0);const [seconds,setSeconds]=useState(0);const [answers,setAnswers]=useState<Record<number,number>>({});const [questionIndex,setQuestionIndex]=useState(0);const [result,setResult]=useState<SessionResult|null>(null);const [full,setFull]=useState(false);const [message,setMessage]=useState('');const [tempoMsg,setTempoMsg]=useState<string|null>(null);const [round,setRound]=useState(0);const [score,setScore]=useState(0);const [revealed,setRevealed]=useState(true);const [roundFeedback,setRoundFeedback]=useState<string|null>(null);const [line,setLine]=useState(0);const [reduceMotion,setReduceMotion]=useState(false);const [picked,setPicked]=useState<number|null>(null);const [animatedWpm,setAnimatedWpm]=useState(0);const [controlsVisible,setControlsVisible]=useState(true);const sessionTip=useMemo(()=>tipForExercise(exercise.id,state.sessions.length),[exercise.id,state.sessions.length]);const introTip=useMemo(()=>tipForExercise(exercise.id,state.sessions.length+1),[exercise.id]);const [guideAuto,setGuideAuto]=useState(true);const [guideWpm,setGuideWpm]=useState(()=>Math.max(80,Math.min(600,Math.round(state.targetWpm/10)*10)));const paperScroll=useRef<ScrollView>(null);const paperY=useRef<number[]>([]);const [paperView,setPaperView]=useState(0);const [eyeMode,setEyeMode]=useState<EyeMode>('lr');const [eyeSpeed,setEyeSpeed]=useState(3);const [eyeSeconds,setEyeSeconds]=useState(60);const [chunkSize,setChunkSize]=useState(3);const [wordLevel,setWordLevel]=useState(2);const [spread,setSpread]=useState(60);const [flashMs,setFlashMs]=useState(400);const [bestSpread,setBestSpread]=useState(0);const [peri,setPeri]=useState<'fixate'|'flash'|'ask'>('fixate');const [record,setRecord]=useState(false);const [variant,setVariant]=useState('');const [skipped,setSkipped]=useState<string[]>([]);const [pendingBaseline,setPendingBaseline]=useState<{wpm:number;comprehension:number}|null>(null);const baselineTries=useRef(0);const [probe,setProbe]=useState(false);const [tune,setTune]=useState(false);const [probes,setProbes]=useState({asked:0,wandered:0});const [previewStep,setPreviewStep]=useState(1);const [repeated,setRepeated]=useState(false);
 const activeMs=useRef(0);const lastTick=useRef(0);const saved=useRef(false);const currentRunId=useRef(createId());const timeout=useRef<ReturnType<typeof setTimeout>|null>(null);const controlTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const [passageSeed,setPassageSeed]=useState(state.sessions.length);const sessionsAtStart=useMemo(()=>state.sessions,[passageSeed]);
 const level=useMemo(()=>longLevel(state.sessions,id=>LONG_PASSAGES.find(p=>p.id===id)?.level),[passageSeed]);
 /** Zelf gekozen tekst (bibliotheek of eigen tekst). Zonder keuze kiest de app uit de centrale bibliotheek. */
 const [chosen,setChosen]=useState<PickedText|null>(()=>{const p=request.passageId?libraryFor(request.exerciseId,state.kidsMode).find(x=>x.id===request.passageId):undefined;return p?{kind:'library',passage:p}:null;});
 /** Oogtraining: versnellen tijdens de sessie, gesproken aanwijzingen bij ontspanning, en de score van de focuswissel. */
 /** Beloning na een oefening: extra XP met reden, een viering en een eventueel nieuw level. */
 const [bonus,setBonus]=useState<string[]>([]);const [celebrate,setCelebrate]=useState<CelebrationSize|null>(null);const [levelUp,setLevelUp]=useState<string|null>(null);const [reveal,setReveal]=useState<{index:number;correct:boolean}|null>(null);
 const [sqQuestion,setSqQuestion]=useState('');const [sqRecite,setSqRecite]=useState('');const [sqAnswered,setSqAnswered]=useState<'ja'|'deels'|'nee'|null>(null);
 const [ramp,setRamp]=useState(true);const [voice,setVoice]=useState(false);const stars=useRef({shown:0,hits:0,wrong:0,current:-1,star:false,hit:-1});const [starFlash,setStarFlash]=useState<null|'hit'|'miss'>(null);
 const ownText=lesson?.params.ownText&&state.texts.length?state.texts[state.texts.length-1]:null;const custom=chosen?.kind==='own'?chosen.text:chosen?null:request.text||ownText;
 const textChoice=choosesText(exercise.id,exercise.mode)&&!request.book;
 const passage=useMemo<Passage>(()=>{if(custom)return {id:custom.id,title:custom.title,text:custom.text,questions:custom.questions?.length?custom.questions:autoQuestions(custom.text)};if(chosen?.kind==='library')return shuffleQuestions(chosen.passage);return shuffleQuestions(pickPassage(textPool(exercise.id,{kids:state.kidsMode,level:exercise.id==='long'?level:undefined}),sessionsAtStart,passageSeed,skipped));},[custom,chosen,passageSeed,sessionsAtStart,state.kidsMode,exercise.id,level,skipped]);
 /** Invulvragen uit je eigen tekst, in plaats van een verzonnen score. */
 const autoQ=!!custom&&!custom.questions?.length;
 const words=useMemo(()=>passage.text.trim().split(/\s+/).filter(Boolean),[passage]);const paragraphs=useMemo(()=>passage.text.split(/\n\n/).filter(Boolean),[passage]);const paperLines=useMemo(()=>{const out=[];for(let i=0;i<words.length;i+=12)out.push(words.slice(i,i+12).join(' '));return out;},[words]);const isPaced=paced.includes(exercise.mode)||(exercise.mode==='innerstem'&&variant==='metronoom'),isGame=games.includes(exercise.mode),isRest=rests.includes(exercise.mode);const restLimit=exercise.mode==='eye'?eyeSeconds:60;const measuredMode=exercise.mode==='reading'||exercise.mode==='paper'||(exercise.mode==='innerstem'&&variant==='kernwoorden')||(exercise.mode==='skim'&&(variant==='previewing'||variant==='sq3r'));
 /** Slim lezen en onthouden (SQ3R): 1 verkennen, 2 vraag stellen, 3 lezen, 4 navertellen, 5 herhalen met de vragen. */
 const sq3r=exercise.mode==='skim'&&variant==='sq3r';const timedLimit=exercise.mode==='skim'?30:0;const firstSentence=(p:string)=>p.match(/^[\s\S]*?[.!?](\s|$)/)?.[0]?.trim()||p;const chunk=isPaced&&!singleWord.includes(exercise.mode)?chunkSize:1;const step=exercise.mode==='chunks'||exercise.mode==='flow'||exercise.mode==='push'?phraseLength(words,cursor,exercise.mode==='flow'?3:chunk):Math.min(chunk,Math.max(1,words.length-cursor));const chunkRange={min:2,max:7};
 // Tempo-push: eerst een sprint over een deel van de tekst, daarna terug naar een tempo dat je aankunt.
 const pushRun=exercise.mode==='push';const push=useMemo(()=>pushPlan(state.sessions),[passageSeed]);const pushWpm=clampWpm(Math.round(state.targetWpm*push.factor/10)*10);const sprintEnd=Math.round(words.length*PUSH.sprintShare);const sprinting=pushRun&&cursor<sprintEnd;const pace=sprinting?pushWpm:tempo;
 /** Wat de app adviseert voor deze oefening; wijk je daarvan af, dan is dat jouw eigen keuze. */
 const recommended=pushRun?clampWpm(Math.round(state.targetWpm*push.lift/10)*10):lesson?.params.tempoFactor?clampWpm(Math.round(state.targetWpm*lesson.params.tempoFactor/10)*10):state.targetWpm;
 const gameItems=useMemo(()=>{const pool=exercise.mode==='wordflash'?wordsForLevel(wordLevel):WORD_GAME_ITEMS;const out=[];while(out.length<10)out.push(...shuffle(pool));return out.slice(0,10);},[passageSeed,wordLevel,exercise.mode]);const item=gameItems[Math.min(round,9)];
 const targetPair=useMemo(()=>{const a=gameItems[Math.min(round,9)].word;const b=gameItems[(round+3)%10].word;return `${a} · ${b}`;},[gameItems,round]);
 const correctOption=isGame&&(exercise.mode==='groups'||exercise.mode==='peripheral')?targetPair:item.word;
 const options=useMemo(()=>shuffle((exercise.mode==='peripheral'||exercise.mode==='groups')?[targetPair,`${item.word} · ${gameItems[(round+5)%10].word}`,`${gameItems[(round+2)%10].word} · ${item.word}`,`${gameItems[(round+1)%10].word} · ${gameItems[(round+6)%10].word}`]:[item.word,...item.distractors.slice(0,3)]),[round,gameItems,targetPair,exercise.mode]);
 const scanTargets=useMemo(()=>shuffle([...new Set(words.map(w=>w.replace(/[^\p{L}]/gu,'')).filter(w=>w.length>5))]).slice(0,5),[words]);const scanTarget=scanTargets[Math.min(round,scanTargets.length-1)];
 const bg=readingBackground(state.settings),dark=readingIsDark(state.settings);const wide=useWindowDimensions().width>=760;
 useEffect(()=>{AccessibilityInfo.isReduceMotionEnabled().then(setReduceMotion);const sub=AccessibilityInfo.addEventListener('reduceMotionChanged',setReduceMotion);return()=>sub.remove();},[]);
 useEffect(()=>{const sub=NativeAppState.addEventListener('change',s=>{if(s!=='active')setPaused(true);});const hide=()=>{if(typeof document!=='undefined'&&document.hidden)setPaused(true);};if(typeof document!=='undefined')document.addEventListener('visibilitychange',hide);return()=>{sub.remove();if(typeof document!=='undefined')document.removeEventListener('visibilitychange',hide);};},[]);
 useEffect(()=>{if(phase!=='reading'||paused)return;lastTick.current=Date.now();const id=setInterval(()=>{const now=Date.now();activeMs.current+=Math.min(now-lastTick.current,500);lastTick.current=now;setSeconds(activeMs.current/1000);},250);return()=>{clearInterval(id);activeMs.current+=Math.min(Math.max(0,Date.now()-lastTick.current),500);};},[phase,paused]);
 useEffect(()=>{if(phase!=='reading'||paused||!isPaced)return;const id=setTimeout(()=>{const next=cursor+step;if(next>=words.length){setCursor(words.length);finishReading(true);}else setCursor(next);},60000/pace*Math.max(1,step));return()=>clearTimeout(id);},[phase,paused,cursor,pace,exercise.id]);
 useEffect(()=>{if(phase!=='reading'||paused||exercise.mode!=='paper'||!guideAuto)return;const id=setTimeout(()=>{if(line>=paperLines.length-1)finishReading(true);else setLine(line+1);},Math.max(900,(paperLines[line]?.split(' ').length??12)/guideWpm*60000));return()=>clearTimeout(id);},[phase,paused,exercise.mode,guideAuto,guideWpm,line,paperLines.length]);
 useEffect(()=>{if(exercise.mode!=='paper'||phase!=='reading')return;const y=paperY.current[line];if(y===undefined)return;paperScroll.current?.scrollTo({y:Math.max(0,y-paperView*.3),animated:!reduceMotion});},[line,phase,exercise.mode,reduceMotion,paperView]);
 useEffect(()=>{if(phase==='reading'&&!paused&&isRest&&seconds>=restLimit)saveResult(null,true,0,eyeTargets?starScore():undefined);},[seconds,phase,paused,restLimit]);
 useEffect(()=>{if(phase!=='reading'||paused||!timedLimit||seconds<timedLimit)return;if(exercise.mode==='skim'&&variant==='previewing'){if(previewStep===1){setPreviewStep(2);activeMs.current=0;setSeconds(0);}return;}if(sq3r){if(previewStep===1)setPreviewStep(2);return;}finishReading(true);},[seconds,phase,paused,timedLimit,variant,previewStep]);
 useEffect(()=>{if(phase!=='reading'||!isGame||paused||roundFeedback||exercise.mode==='peripheral')return;setRevealed(true);if(exercise.mode==='catcher')return;const id=setTimeout(()=>setRevealed(false),exercise.mode==='wordflash'?wordLevelSpec(wordLevel).flashMs:state.kidsMode?1800:1400);return()=>clearTimeout(id);},[round,phase,paused,exercise.mode,roundFeedback,wordLevel]);
 /**
  * Perifeer zien in drie stappen per ronde: fixeren (700 ms), flitsen (precies de gekozen flitstijd) en vragen.
  * De woorden van de ronde staan al onzichtbaar klaar; de flits verandert alleen de zichtbaarheid.
  * De flitsduur meten we per beeldje, zodat ook 100 ms echt 100 ms is.
  */
 useEffect(()=>{if(phase!=='reading'||exercise.mode!=='peripheral'||roundFeedback)return;
  if(paused){if(peri==='flash')setPeri('fixate');return;}
  if(peri==='fixate'){const id=setTimeout(()=>setPeri('flash'),700);return()=>clearTimeout(id);}
  if(peri==='flash'){let frame=0;const t0=Date.now();const tick=()=>{if(Date.now()-t0>=flashMs-8)setPeri('ask');else frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);}
 },[round,phase,paused,roundFeedback,peri,flashMs,exercise.mode]);
 useEffect(()=>{const p=lesson?.params||{};setChunkSize(p.chunk??(['chunks','fixation','forward'].includes(exercise.mode)?3:exercise.mode==='push'?2:1));setTempo(recommended);setSpread(state.prefs.spread??p.spread??60);setFlashMs(state.prefs.flashMs??p.flashMs??400);setTune(exercise.mode==='peripheral');if(p.guideAuto!==undefined)setGuideAuto(p.guideAuto);setEyeMode(p.eyeMode??(exercise.id==='eight'?'eight':exercise.id==='focusswitch'?'targets':'lr'));setEyeSpeed(state.prefs.eyeSpeed??(exercise.id==='focusswitch'?3:4));setVoice(exercise.id==='palming');setVariant(p.variant??(exercise.id==='sq3r'?'sq3r':exercise.mode==='skim'?'skimmen':exercise.mode==='innerstem'?'metronoom':''));tempoTouched.current=false;},[exercise.id,dailyStep,passageSeed]);
 useEffect(()=>()=>{if(timeout.current)clearTimeout(timeout.current);if(controlTimer.current)clearTimeout(controlTimer.current);},[]);
 useEffect(()=>{if(phase!=='result'||!result)return;const goal=result.wpm;if(reduceMotion){setAnimatedWpm(goal);return;}const start=Date.now();const id=setInterval(()=>{const t=Math.min(1,(Date.now()-start)/750);setAnimatedWpm(Math.round(goal*(1-Math.pow(1-t,3))));if(t>=1)clearInterval(id);},25);return()=>clearInterval(id);},[phase,result,reduceMotion]);
 function revealControls(){setControlsVisible(true);if(controlTimer.current)clearTimeout(controlTimer.current);if(!paused)controlTimer.current=setTimeout(()=>setControlsVisible(false),3000);}
 function start(){setSqQuestion('');setSqRecite('');setSqAnswered(null);stars.current={shown:0,hits:0,wrong:0,current:-1,star:false,hit:-1};setStarFlash(null);setPeri('fixate');setProbes({asked:0,wandered:0});setProbe(false);setPreviewStep(1);setPhase('reading');setPaused(false);setCursor(0);setLine(0);setSeconds(0);setAnswers({});setQuestionIndex(0);setRound(0);setScore(0);setResult(null);setMessage('');setFull(false);saved.current=false;activeMs.current=0;currentRunId.current=createId();revealControls();}
 function finishReading(complete:boolean){if(saved.current)return;const dur=activeMs.current/1000;if(dur<3){setMessage('Neem rustig de tijd om de tekst te lezen.');return;}const rejected=complete&&measuredMode&&exercise.mode!=='paper'?readingRejection(words.length,dur,state.kidsMode):null;if(rejected){setMessage(rejected);return;}setFull(complete);setPaused(false);if(complete&&sq3r){setPhase('recite');return;}if(complete&&passage.questions.length&&exercise.mode!=='scan'){setPhase('quiz');setAnswers({});setQuestionIndex(0);}else saveResult(null,complete,isPaced?Math.min(words.length,cursor):words.length);}
 function saveResult(comprehension:number|null,complete:boolean,readWords?:number,recognitionScore?:number){if(saved.current)return;const dur=Math.max(.1,activeMs.current/1000);let read=readWords??(complete?words.length:cursor);const measured=measuredMode;const wpm=isRest||isGame||exercise.mode==='scan'||(!measured&&!isPaced)?0:measured||pushRun?Math.round(read/dur*60):tempo;
 if(!isRest&&!isGame&&exercise.mode!=='scan'&&(read<10||dur<3)){setMessage('Lees minstens 10 woorden voordat je deze oefening afrondt.');return;}
 saved.current=true;setFull(complete);const passageId=isGame||isRest?undefined:passage.id;const repeat=repeatFactor(state.sessions,passageId);const ok=passed(complete,comprehension);
 // Een record telt alleen met voldoende begrip; snelheid alleen levert geen record op.
 const isRec=measured&&ok&&isRecord(state.sessions,{exerciseId:exercise.id,wpm,comprehension});setRecord(isRec);setRepeated(repeat<1);
 const r:SessionResult={id:currentRunId.current,exerciseId:exercise.id,skill:exercise.skill,wpm,comprehension,words:Math.max(0,read),durationSeconds:dur,date:new Date().toISOString(),xp:xpFor({complete,comprehension,repeat}),...(passageId?{passageId}:{}),...(ok&&(request.daily||request.baseline)?{dailyId:dayKey}:{}),...(ok&&lesson?{lessonDay:daily.day}:{}),...(probes.asked?{probes:probes.asked,wandered:probes.wandered}:{}),...(pushRun?{pushWpm}:{}),...(recognitionScore!==undefined?{score:eyeTargets?recognitionScore:recognitionScore*10}:{})};
 // Eén tempobesluit: de melding hieronder en het tempo van je volgende oefening komen allebei hieruit.
 let decision:TempoDecision;
 if((request.baseline||exercise.id==='baseline')&&!state.baseline){decision=keepTempo(state);if(comprehension!==null){baselineTries.current+=1;if(baselineAccepted(comprehension,baselineTries.current)){setBaseline({wpm,comprehension});decision=keepTempo(state,baselineTarget(wpm,state.kidsMode));}else setPendingBaseline({wpm,comprehension});}}
 // Bij een push is te weinig begrip in de sprint verwacht; dat verlaagt je oefentempo niet. Goed begrip telt wel mee.
 else if(pushRun){const d=decideTempo(state,r.comprehension,undefined,tempoTouched.current?tempo:undefined);decision=d.reason==='begrip-laag'?keepTempo(state):d;}
 else decision=decideTempo(state,r.comprehension,r.probes?{asked:r.probes,wandered:r.wandered??0}:undefined,isPaced&&tempoTouched.current?tempo:undefined);
 // Perifeer zien groeit mee: de volgende ronde begint op de afstand waar je nu eindigde.
 if(exercise.mode==='peripheral')updatePrefs({spread});
 if(request.book){const reached=reachedParagraph(request.book,read,complete);if(reached.para>request.book.from)setBookPosition(request.book.id,reached.para,request.book.startWords+reached.words);}
 const ch=challengeOfDay();const challengeNow=!challengeDone(state.sessions,ch)&&meetsChallenge(ch,{...r,tempoFrom:decision.from});
 const lessonNow=ok&&!!lesson&&!pathProgress(state.sessions).completed.includes(daily.day);
 const extra=bonusXp({lessonPassed:lessonNow,record:isRec,challenge:challengeNow,firstToday:complete&&!state.sessions.some(x=>dateKey(x.date)===dateKey())});
 const stored:SessionResult={...r,xp:r.xp+extra.xp,tempoFrom:decision.from,tempoTo:decision.to};
 const before=levelFor(app.stats.totalXP),after=levelFor(app.stats.totalXP+stored.xp);
 setBonus(extra.reasons);setLevelUp(after.level>before.level?`Level ${after.level} · ${after.title}`:null);
 setCelebrate(isRec||after.level>before.level?'medium':challengeNow||lessonNow?'medium':ok&&(comprehension??0)>=80?'small':null);
 setTempoMsg(tempoNote(decision));addSession(stored,decision);setResult(stored);setPhase('result');setPaused(false);if(recognitionScore!==undefined)setScore(recognitionScore);
 }
 function submitAnswer(value:number){const next={...answers,[questionIndex]:value};setAnswers(next);if(questionIndex+1<passage.questions.length)setQuestionIndex(questionIndex+1);else{const correct=passage.questions.reduce((n,q,i)=>n+(next[i]===q.answer?1:0),0);saveResult(Math.round(correct/passage.questions.length*100),true,words.length);}}
 function gameAnswer(option:string){if(roundFeedback||paused)return;const correct=option===correctOption;const nextScore=score+(correct?1:0);setScore(nextScore);if(exercise.mode==='peripheral'){if(correct)setBestSpread(b=>Math.max(b,spread));setSpread(v=>Math.max(20,Math.min(95,v+(correct?5:-5))));}setRoundFeedback(correct?'Goed gezien.':`Het was: ${correctOption}`);if(correct)setCelebrate('small');timeout.current=setTimeout(()=>{setRoundFeedback(null);setPeri('fixate');if(exercise.mode!=='catcher')setRevealed(true);if(round>=9)saveResult(null,true,10,nextScore);else setRound(round+1);},900);}
 function scanAnswer(word:string){if(paused)return;if(word.replace(/[^\p{L}]/gu,'')===scanTarget){if(round+1>=scanTargets.length)saveResult(null,true,scanTargets.length);else setRound(round+1);setMessage('');}else setMessage('Bijna. Zoek het woord '+scanTarget+'.');}
 /** Bij lange teksten en boeken vragen we af en toe of je er nog bij was. Afdwalen merken is de eerste stap om het minder te doen. */
 const probeOn=!!request.book||exercise.id==='long';
 useEffect(()=>{if(phase==='result'&&result&&passed(full,result.comprehension))feel.done();},[phase]);
 useEffect(()=>{if(!probeOn||phase!=='reading'||paused||probe)return;if(Math.floor(seconds/PROBE_SECONDS)>probes.asked){setProbe(true);setPaused(true);}},[seconds,phase,paused,probe,probes.asked,probeOn]);
 function answerProbe(wandered:boolean){setProbes(p=>({asked:p.asked+1,wandered:p.wandered+(wandered?1:0)}));setProbe(false);setPaused(false);}
 /** Wissel naar een andere tekst: deze ronde telt niet mee en begint opnieuw. */
 function otherText(restart:boolean){setChosen(null);setSkipped(s=>[...s,passage.id]);if(restart)start();}
 const canSwap=!custom&&!isRest&&!isGame&&textChoice;
 function retry(){if(chosen?.kind==='library')setChosen(null);setPhase('intro');setPassageSeed(passageSeed+1);setResult(null);saved.current=false;setMessage('');}
 function next(){setChosen(null);setDailyStep(dailyStep+1);setPhase('intro');setPassageSeed(passageSeed+1);setResult(null);saved.current=false;setMessage('');}
 /** Focuswissel: elk nieuw doel telt; tik je bij een ster, dan is dat raak. Tik je zonder ster, dan is het mis. */
 const eyeTargets=exercise.mode==='eye'&&eyeMode==='targets';
 function onTarget(index:number,star:boolean){const st=stars.current;st.current=index;st.star=star;if(star)st.shown+=1;}
 function tapStar(){const st=stars.current;if(st.star&&st.hit!==st.current){st.hit=st.current;st.hits+=1;setStarFlash('hit');feel.tap();}else{st.wrong+=1;setStarFlash('miss');}setTimeout(()=>setStarFlash(null),450);}
 /** Nauwkeurigheid: goede tikken gedeeld door alle sterren plus alle vergissingen. */
 function starScore(){const st=stars.current;return Math.round(st.hits/Math.max(1,st.shown+st.wrong)*100);}
 function quit(){if(phase==='reading'||phase==='quiz'){setPaused(true);setConfirmExit(true);}else onClose();}
 const sessionLabel=request.daily?`${dayLesson?`DAG ${daily.day} · `:'DAGTRAINING · '}${Math.min(dailyStep+1,steps)} VAN ${steps}`:request.baseline?'JOUW VERTREKPUNT':'EEN MOMENT VOOR JEZELF';
 if(request.daily&&dailyStep>=steps)return <DayComplete day={daily.day} lesson={dayLesson} lessonDone={!!dayLesson&&pathProgress(state.sessions).completed.includes(daily.day)} sessions={state.sessions} streak={app.stats.streak} onClose={onClose}/>;
 if(phase==='intro')return <Screen style={{maxWidth:680}} footer={<><Button title={request.baseline?'Start mijn begintest':'Ik ben er klaar voor'} icon="play" onPress={start}/><T variant="caption" style={{textAlign:'center'}}>Je kunt op ieder moment pauzeren.</T></>}><BackHeader title={request.daily?'Jouw dagtraining':lesson?exercise.title:''} onBack={onClose}/>{lesson?<View style={{gap:10,paddingTop:6}}><Pill label={sessionLabel}/><T variant="display" style={{fontSize:34,lineHeight:40}}>{lesson.title}</T><Row><Icon name={exercise.icon} size={16} color={colors.accent}/><T variant="label" style={{flex:1}}>{custom?custom.title:exercise.title}</T><T variant="caption">{exercise.minutes} min</T></Row></View>:<View style={{alignItems:'center',gap:21,paddingVertical:20}}><Pill label={sessionLabel}/><Illustration name={exercise.skill==='focus'?'focus':exercise.skill} size={128}/><T variant="display" style={{fontSize:38,lineHeight:43,textAlign:'center'}}>{custom?custom.title:exercise.title}</T><T color={ui.muted} style={{textAlign:'center',maxWidth:460}}>{exercise.description}</T><Row><Pill label={`${exercise.minutes} min`} icon="clock" background={colors.surface} color={ui.muted}/>{exercise.id==='long'&&!custom&&<Pill label={`Niveau ${LONG_LEVELS[level-1]}`} icon="chart" background={colors.surface} color={ui.muted}/>}<Pill label={custom?'Eigen tekst':state.kidsMode?'Kort verhaal':'Op jouw tempo'} icon="leaf" background={colors.surface} color={ui.muted}/></Row></View>}
 {lesson&&<Card style={{backgroundColor:ui.forestSoft,borderWidth:0,gap:12}}><T style={{fontSize:15,lineHeight:23}}>{lesson.what}</T><T color={ui.muted} style={{fontSize:15,lineHeight:23}}>{lesson.why}</T><View style={{height:1,backgroundColor:ui.line}}/><T variant="label">Zo pas je het nu toe</T><T style={{fontSize:15,lineHeight:23}}>{lesson.how}</T></Card>}
 {request.daily&&dailyStep>0&&<Card style={{backgroundColor:colors.tintLilac,borderWidth:0,gap:10}}><Row><Icon name={dayLesson?'checkcircle':sessionTip.icon} size={18} color={colors.accent}/><T variant="label">{dayLesson?'Pas toe wat je net leerde':'Even tussendoor'}</T></Row><T variant="heading" style={{fontSize:19}}>{dayLesson?dayLesson.title:sessionTip.title}</T><T style={{fontSize:15}}>{dayLesson?dayLesson.hint:sessionTip.body}</T><T variant="caption">Neem dit mee in de oefening hierna.</T></Card>}
 {!request.daily&&!request.baseline&&<Card style={{gap:8,backgroundColor:colors.tintLilac,borderWidth:0}}><Row><Icon name={introTip.icon} size={17} color={colors.accent}/><T variant="label" style={{flex:1}}>Tip · {introTip.title}</T></Row><T variant="caption" style={{fontSize:14,lineHeight:21}}>{introTip.body}</T></Card>}
 {exercise.mode==='innerstem'&&<Card style={{gap:14,backgroundColor:colors.surface,borderWidth:0}}><Choice label="Zo lees je" value={variant} options={[{value:'metronoom',label:'Metronoom'},{value:'kernwoorden',label:'Kernwoorden'}]} onChange={setVariant}/><T variant="caption">{variant==='metronoom'?'Lees mee op een gelijkmatig ritme, een fractie sneller dan praten. Je binnenstem mag meelopen, als een fluistering. Verhoog pas als je de hoofdgedachte nog kunt navertellen.':'Lees de tekst in je eigen tempo en laat je binnenstem alleen de woorden benadrukken die de betekenis dragen. De kleine woordjes glijden erlangs. Daarna volgen vragen.'}</T><T variant="caption">Je binnenstem helpt je begrijpen. Het doel is een lichtere stem, geen stille.</T></Card>}
 {exercise.id==='sq3r'&&<Card style={{gap:12,backgroundColor:colors.surface,borderWidth:0}}><T variant="label">Vijf stappen</T>{[['Verkennen','30 seconden: titel en eerste zinnen. Waar gaat het over?'],['Vragen stellen','Wat wil je uit deze tekst halen?'],['Lezen','De hele tekst, op je eigen tempo, met je vraag in gedachten.'],['Navertellen','In een paar zinnen, zonder terug te kijken.'],['Herhalen','Met de vragen kijk je wat er is blijven hangen.']].map(([t,b],i)=><Row key={t} style={{alignItems:'flex-start'}}><View style={[s.optionCircle,{width:28,height:28,borderRadius:14}]}><T variant="caption" color={colors.accent}>{i+1}</T></View><View style={{flex:1}}><T variant="label" style={{fontSize:14}}>{t}</T><T variant="caption">{b}</T></View></Row>)}<T variant="caption">In het Engels heet dit SQ3R: survey, question, read, recite, review.</T></Card>}
 {exercise.mode==='skim'&&exercise.id!=='sq3r'&&<Card style={{gap:14,backgroundColor:colors.surface,borderWidth:0}}><Choice label="Kies je aanpak" value={variant} options={[{value:'skimmen',label:'Skimmen'},{value:'previewing',label:'Previewing'}]} onChange={setVariant}/><T variant="caption">{variant==='skimmen'?'De kernzinnen zijn gemarkeerd. Je hebt 30 seconden om de hoofdgedachte te vangen zonder alles te lezen. Daarna volgen de vragen.':'Stap 1: 30 seconden alleen de titel en de eerste zin van elke alinea. Stap 2: de hele tekst lezen. Daarna volgen de vragen.'}</T></Card>}
 {textChoice&&<TextPicker current={{title:passage.title,words:words.length,own:!!custom,topic:custom?undefined:(chosen?.kind==='library'?chosen.passage:passage).topic,level:custom?undefined:passage.level}} library={libraryFor(exercise.id,state.kidsMode)} texts={state.texts} initialTab={lesson?.params.ownText?(state.texts.length?undefined:'new'):undefined} note={lesson?.params.ownText?(state.texts.length?'Je oefent met je laatst bewaarde tekst. Kies hierboven een andere, of voeg een nieuwe toe.':'Voeg je eigen tekst toe: plakken, typen of via een link.'):undefined} minWords={isPaced?30:20} onAuto={()=>otherText(false)} onPickLibrary={p=>setChosen({kind:'library',passage:p})} onPickOwn={t=>setChosen({kind:'own',text:t})} onNew={({title,text,keep})=>{const t=keep?app.saveText({title,text}):{id:`los-${createId()}`,title,text,createdAt:new Date().toISOString()};setChosen({kind:'own',text:t});}}/>}{request.book&&<Row style={{paddingHorizontal:4}}><Icon name="bookmark" size={16} color={colors.accent}/><T variant="label" numberOfLines={1} style={{flex:1}}>{passage.title}</T></Row>}
 {pushRun&&<Card style={{gap:10,backgroundColor:colors.tintSun,borderWidth:0}}><Row><Icon name="zap" size={18} color={colors.accent}/><T variant="label" style={{flex:1}}>Sprint {pushWpm} wpm, daarna {tempo} wpm</T></Row><T variant="caption">De eerste {Math.round(PUSH.sprintShare*100)}% van de tekst lees je in sprinttempo. Daarna zakt het tempo terug. Begrip telt mee: na afloop volgen vragen.</T>{!!push.note&&<T variant="caption">{push.note}</T>}</Card>}
 {(isPaced||['paper','eye','wordflash','peripheral','relax'].includes(exercise.mode))&&<Card style={{gap:16,backgroundColor:colors.surface,borderWidth:0}}><Pressable accessibilityRole="button" accessibilityState={{expanded:tune}} accessibilityLabel="Oefening aanpassen" onPress={()=>setTune(!tune)} style={{flexDirection:'row',alignItems:'center',gap:12,minHeight:44}}><Icon name="settings" size={18} color={colors.accent}/><View style={{flex:1}}><T variant="label">Aanpassen</T><T variant="caption">{(isPaced?`${tempo} wpm${tempo!==recommended?' · eigen keuze':' · aanbevolen'}${exercise.mode!=='innerstem'&&exercise.mode!=='flow'?` · ${chunk} ${exercise.mode==='chunks'||pushRun?'woorden per groep':chunk===1?'woord per keer':'woorden per keer'}`:''}`:exercise.mode==='paper'?(guideAuto?`De gids loopt vanzelf mee · ${guideWpm} wpm`:'Je gaat zelf verder'):exercise.mode==='eye'?`${EYE_MODES.find(m=>m.value===eyeMode)?.label??''} · snelheid ${eyeSpeed}${ramp?' · versnelt':''} · ${eyeSeconds/60} min`:exercise.mode==='relax'?(voice?'Met gesproken aanwijzingen':'Met een trilling bij elke wissel'):exercise.mode==='peripheral'?`${spread}% breed · ${flashMs} ms`:WORD_LEVELS.find(l=>l.level===wordLevel)?.title??'')}</T></View><Icon name={tune?'minus':'plus'} size={18} color={ui.dim}/></Pressable>{tune&&<View style={{gap:16}}>
 {isPaced&&<View style={{gap:15}}><Row style={{justifyContent:'space-between'}}><T variant="label">{pushRun?'Tempo na de sprint':'Een prettig oefentempo'}</T><Icon name="zap" size={19} color={colors.accent}/></Row><TempoSource tempo={tempo} recommended={recommended} onReset={()=>{tempoTouched.current=false;setTempo(recommended);}}/><Row style={{justifyContent:'center',gap:28}}><IconButton name="minus" label="Tempo verlagen" onPress={()=>{tempoTouched.current=true;setTempo(Math.max(60,tempo-20));}}/><View style={{alignItems:'center'}}><T variant="stat">{tempo}</T><T variant="caption">woorden per minuut</T></View><IconButton name="plus" label="Tempo verhogen" onPress={()=>{tempoTouched.current=true;setTempo(Math.min(800,tempo+20));}}/></Row></View>}
 {isPaced&&exercise.mode!=='innerstem'&&exercise.mode!=='flow'&&!singleWord.includes(exercise.mode)&&<View style={{gap:24}}><Stepper label="Woorden per keer" icon="text" value={chunkSize} unit={exercise.mode==='chunks'||pushRun?'woorden, geknipt per zinsdeel':'woorden tegelijk'} min={chunkRange.min} max={chunkRange.max} step={1} onChange={setChunkSize}/></View>}
 {exercise.mode==='paper'&&<View style={{gap:22}}><Choice label="De gids" value={guideAuto?'auto':'zelf'} options={[{value:'zelf',label:'Ik ga zelf verder'},{value:'auto',label:'Loopt vanzelf mee'}]} onChange={v=>setGuideAuto(v==='auto')}/>{guideAuto&&<Stepper label="Tempo van de gids" icon="clock" value={guideWpm} unit="woorden per minuut" min={80} max={600} step={10} onChange={setGuideWpm}/>}</View>}
 {exercise.mode==='relax'&&<Choice label="Aanwijzingen" value={voice?'stem':'stil'} options={[{value:'stil',label:'Trilling en beeld'},{value:'stem',label:'Ook een stem'}]} onChange={v=>setVoice(v==='stem')}/>}
 {exercise.mode==='eye'&&<View style={{gap:22}}><Choice label="Patroon" value={eyeMode} options={EYE_MODES} onChange={setEyeMode}/><Slider label="Snelheid" value={eyeSpeed} unit="van 10" min={1} max={10} step={1} onChange={v=>{setEyeSpeed(v);updatePrefs({eyeSpeed:v});}}/><Choice label="Tijdens de sessie" value={ramp?'ramp':'vast'} options={[{value:'ramp',label:'Geleidelijk sneller'},{value:'vast',label:'Vast tempo'}]} onChange={v=>setRamp(v==='ramp')}/><Choice label="Duur" value={String(eyeSeconds)} options={[{value:'60',label:'1 minuut'},{value:'180',label:'3 minuten'},{value:'360',label:'6 minuten'}]} onChange={v=>setEyeSeconds(Number(v))}/></View>}
 {exercise.mode==='wordflash'&&<View style={{gap:16}}><Choice label="Niveau" value={String(wordLevel)} options={WORD_LEVELS.map(l=>({value:String(l.level),label:l.title}))} onChange={v=>setWordLevel(Number(v))}/><T variant="caption">Langere woorden krijgen een kortere flits.</T></View>}
 {exercise.mode==='peripheral'&&<View style={{gap:24}}><Slider label="Flitstijd" value={flashMs} unit="ms" min={80} max={1200} step={20} onChange={v=>{setFlashMs(v);updatePrefs({flashMs:v});}} hint={`Hoe korter, hoe uitdagender.${lesson?.params.flashMs?` Advies van deze les: ${lesson.params.flashMs} ms.`:''} Je keuze wordt bewaard en geldt ook in de leerweg.`}/><Slider label="Afstand tussen de woorden" value={spread} unit="%" min={20} max={95} step={5} onChange={v=>{setSpread(v);updatePrefs({spread:v});}} hint="Groeit mee als je goed scoort en zakt een stapje als het te veel wordt. Vanaf 70% springen de woorden ook in hoogte."/></View>}
 </View>}</Card>}
 {request.daily&&<Card style={{gap:14}}>{plan.map((e,i)=><Row key={i}><View style={{width:30,height:30,borderRadius:15,backgroundColor:i===dailyStep?colors.accent:colors.surface,alignItems:'center',justifyContent:'center'}}>{i<dailyStep?<Icon name="check" size={16} color={colors.accent}/>:<T variant="caption" color={i===dailyStep?colors.bg:ui.muted}>{i+1}</T>}</View><T variant="label" style={{flex:1}}>{e.title}</T><T variant="caption">{e.minutes} min</T></Row>)}</Card>}
 </Screen>;
 if(phase==='result'&&result){const ok=passed(full,result.comprehension);const dailyMore=request.daily&&ok&&dailyStep<steps-1;const firstLesson=!!onDaily&&request.baseline&&!request.daily&&ok&&daily.day===1&&!daily.doneToday;const primary=firstLesson?<><Button title="Verder met je eerste les" icon="arrow" onPress={onDaily}/><T variant="caption" style={{textAlign:'center'}}>Nog twee korte oefeningen van een minuut. De begintest telt al mee.</T><Button title="Later" secondary onPress={onClose}/></>:<><Button title={dailyMore?'Verder met mijn volgende oefening':request.daily&&!ok?'Probeer het opnieuw met een nieuwe tekst':request.daily&&dailyStep>=steps-1?'Rond mijn dagsessie af':request.book?'Terug naar je boek':'Terug naar mijn leesplek'} icon="arrow" onPress={()=>dailyMore||(request.daily&&ok&&dailyStep>=steps-1)?next():request.daily&&!ok?retry():onClose()}/>{request.daily&&!ok&&<Button title="Stop voor vandaag" secondary onPress={onClose}/>}</>;return <Screen style={{maxWidth:680}} footer={pendingBaseline?undefined:primary}><View style={{alignItems:'center',gap:16,paddingTop:20}}><Pill label={pendingBaseline?'BIJNA':request.daily?`OEFENING ${dailyStep+1} VAN 3`:'MOOI GEDAAN'} icon={pendingBaseline?'refresh':'check'}/><Illustration name="resultaat-hero" size={145}/>{record&&<Pill label={`PERSOONLIJK RECORD · BIJ ${result.comprehension}% BEGRIP`} icon="trophy" background={colors.tintSun} color={ui.forestInk}/>}{!!levelUp&&<Pill label={`NIEUW LEVEL · ${levelUp.toLocaleUpperCase('nl')}`} icon="star" background={colors.tintSun} color={ui.forestInk}/>}<T variant="title" style={{textAlign:'center'}}>{pendingBaseline?'Nog één keer, rustiger?':request.baseline||exercise.id==='baseline'?'Je vertrekpunt staat.':!full?'Een klein stukje is ook een begin.':!ok?'Nog even oefenen.':'Een moment om trots op te zijn.'}</T><T color={ui.muted} style={{textAlign:'center'}}>{pendingBaseline?`Je begreep ${pendingBaseline.comprehension}% van de tekst. Een vertrekpunt is pas eerlijk als je ook begrijpt wat je leest, anders lijk je later niet vooruit te gaan. Lees de volgende tekst op je gewone tempo.`:request.baseline?'Dit is jouw vertrekpunt. Van hieruit gaan we rustig verder.':!full?'Je hebt de oefening eerder afgerond. Je oefentijd is bewaard.':!ok?`Onder ${COMPREHENSION_GATE}% begrip telt een ronde als oefening. Je krijgt oefen-XP, maar de les en je record blijven staan.`:result.comprehension!==null&&result.wpm>0?`Je las ${result.wpm} woorden per minuut en begreep ${result.comprehension}% van de tekst.`:'Je hebt aandacht gegeven aan je leesritme. Dat telt.'}</T></View>
 {sq3r&&(!!sqQuestion.trim()||!!sqRecite.trim())&&<Card style={{gap:10,backgroundColor:ui.forestSoft,borderWidth:0}}><T variant="label">Jouw vijf stappen</T>{!!sqQuestion.trim()&&<T variant="caption">Vraag: {sqQuestion}{sqAnswered?` · beantwoord: ${sqAnswered}`:''}</T>}{!!sqRecite.trim()&&<T style={{fontSize:15,lineHeight:22}}>{sqRecite}</T>}<T variant="caption">Herhaal morgen nog even je samenvatting: dan onthoud je het nog beter.</T></Card>}
 {probes.asked>0&&<Card style={{gap:8,backgroundColor:ui.subtle,borderWidth:0}}><Row><Icon name="eye" size={18} color={colors.accent}/><T variant="label">{probes.wandered===0?`Je was er ${probes.asked===1?'bij de check':`alle ${probes.asked} keer`} bij.`:`Je dwaalde ${probes.wandered} van de ${probes.asked} keer af.`}</T></Row><T variant="caption">{probes.wandered===0?'Mooi. Blijf merken wanneer je aandacht wegzakt, zeker bij een lange tekst.':'Dat is heel gewoon. Merk je het tijdens het lezen? Ga dan terug naar het begin van de alinea en lees rustig door.'}</T></Card>}
 {pendingBaseline&&<Card style={{gap:12,backgroundColor:ui.forestSoft,borderWidth:0}}><Button title="Nog een keer, rustiger" icon="refresh" onPress={()=>{setPendingBaseline(null);retry();}}/><Button title="Toch als vertrekpunt gebruiken" secondary onPress={()=>{setBaseline(pendingBaseline);setPendingBaseline(null);}}/><T variant="caption">Vanaf {BASELINE_MIN}% begrip telt je begintest meteen. De tweede keer telt hij altijd.</T></Card>}
 <Card style={{backgroundColor:colors.surface,borderWidth:0,alignItems:'center',gap:5,padding:28}}><T variant="display" style={{fontSize:68,lineHeight:76}}>{result.wpm?animatedWpm:result.score!==undefined&&!isGame?`${result.score}%`:isGame?`${score}/10`:exercise.mode==='scan'?scanTargets.length:Math.round(result.durationSeconds)}</T><T variant="caption">{result.score!==undefined&&!isGame?`nauwkeurigheid · ${stars.current.hits} van ${stars.current.shown} sterren, ${stars.current.wrong} keer mis`:result.wpm?(measuredMode?'woorden per minuut · gemeten':'woorden per minuut · oefentempo'):isGame?(exercise.mode==='peripheral'?`woordparen herkend · tot ${bestSpread||spread}% afstand bij ${flashMs} ms · volgende keer start je op ${spread}%`:'woorden of woordgroepen herkend'):exercise.mode==='scan'?'zoekwoorden gevonden':isRest?'seconden rust en aandacht':'seconden gelezen'}</T></Card><Row style={{gap:14}}><Card style={{flex:1,alignItems:'center',gap:5,backgroundColor:ui.subtle,borderWidth:0}}><T variant="stat">{result.comprehension===null?'—':`${result.comprehension}%`}</T><T variant="caption">{result.comprehension===null?'begrip niet gemeten':'tekstbegrip'}</T></Card><Card style={{flex:1,alignItems:'center',gap:5,backgroundColor:ui.subtle,borderWidth:0}}><T variant="stat">+{result.xp}</T><T variant="caption">{repeated?'lees-XP · deze tekst las je vandaag al':'lees-XP'}</T></Card></Row>{bonus.length>0&&<Row style={{flexWrap:'wrap',justifyContent:'center',gap:8}}>{bonus.map(b=><Pill key={b} label={b} icon="sparkles" background={colors.surface} color={ui.muted}/>)}</Row>}
 {lesson&&<Card style={{backgroundColor:ui.forestSoft,borderWidth:0,gap:10}}><Row><Icon name="sparkles" size={18} color={colors.accent}/><T variant="label">{`Dag ${daily.day} · ${lesson.title}`}</T></Row><T style={{fontSize:15,lineHeight:23}}>{lessonFeedback(lesson,{wpm:result.wpm,comprehension:result.comprehension,score:isGame?score:undefined,baselineEffective:state.baseline&&exercise.id!=='baseline'?effectiveWpm(state.baseline.wpm,state.baseline.comprehension):undefined})}</T></Card>}
 <Card style={{backgroundColor:colors.tintLilac,borderWidth:0,gap:10}}><Row><Icon name={sessionTip.icon} size={18} color={colors.accent}/><T variant="label">{sessionTip.title}</T></Row><T style={{fontSize:15}}>{sessionTip.body}</T>{tempoMsg?<Row style={{alignItems:'flex-start'}}><Icon name="zap" size={16} color={colors.accent}/><T variant="caption" style={{flex:1}}>{tempoMsg}</T></Row>:result.comprehension!==null&&<T variant="caption">{result.comprehension>=80?'Je nam de inhoud goed mee. Blijf dit tempo volgen zolang het prettig voelt.':'Begrip en tempo zoeken nog hun balans. Dat hoort erbij.'}</T>}</Card>
 {request.book&&(()=>{const b=state.books.find(x=>x.id===request.book!.id);return b?<Card style={{gap:10,backgroundColor:ui.forestSoft,borderWidth:0}}><Row style={{justifyContent:'space-between'}}><T variant="label" numberOfLines={1} style={{flex:1}}>{b.title}</T><T variant="label" color={colors.accent}>{Math.round(bookProgress(b)*100)}%</T></Row><ProgressBar value={bookProgress(b)}/><T variant="caption">Je bladwijzer staat waar je gebleven bent.</T></Card>:null;})()}
 {result.comprehension!==null&&passage.questions.some((q,i)=>answers[i]!==q.answer)&&<Card style={{gap:12}}><T variant="label">Even terug naar de inhoud</T>{passage.questions.map((q,i)=>answers[i]!==q.answer?<View key={i} style={{gap:4}}><T variant="caption">{q.question}</T><T variant="label" style={{fontSize:14}}>{q.options[q.answer]}</T></View>:null)}</Card>}
 {!state.profile.name&&onProfile&&!dailyMore&&<Button title="Maak mijn leesplek persoonlijk" secondary onPress={onProfile}/>}{celebrate&&<Celebration size={celebrate} onDone={()=>setCelebrate(null)}/>}</Screen>;}
 if(phase==='recite')return <Screen style={{maxWidth:680}} footer={<Button title={passage.questions.length?'Stap 5: herhaal met de vragen':'Rond af'} icon="arrow" onPress={()=>{if(passage.questions.length){setPhase('quiz');setAnswers({});setQuestionIndex(0);}else saveResult(null,true,words.length);}}/>}><Row><IconButton name="close" label="Stoppen met deze oefening" onPress={quit}/><Pill label="STAP 4 VAN 5 · NAVERTELLEN" icon="text"/></Row><T variant="title" style={{fontSize:27,lineHeight:33}}>Vertel in een paar zinnen wat je las.</T><T color={ui.muted}>Zonder terug te kijken. Wat was de kern, en wat onthoud je? Navertellen zet de tekst vast in je geheugen en laat zien wat nog niet duidelijk was.</T><TextInput accessibilityLabel="Jouw samenvatting" placeholder="De tekst gaat over…" placeholderTextColor={ui.dim} value={sqRecite} onChangeText={setSqRecite} multiline textAlignVertical="top" style={[s.input,{minHeight:130}]} maxLength={1000}/>{!!sqQuestion.trim()&&<Card style={{gap:10}}><T variant="caption">Jouw vraag was</T><T variant="label">{sqQuestion}</T><Choice label="Heeft de tekst je vraag beantwoord?" value={sqAnswered??''} options={[{value:'ja',label:'Ja'},{value:'deels',label:'Deels'},{value:'nee',label:'Nee'}]} onChange={v=>setSqAnswered(v as 'ja'|'deels'|'nee')}/></Card>}<T variant="caption">Wat je hier typt blijft op dit apparaat en wordt niet bewaard na deze oefening.</T>{confirmExit&&<ExitConfirm onCancel={()=>{setConfirmExit(false);setPaused(false);}} onExit={onClose}/>}</Screen>;
 if(phase==='quiz'){const q=passage.questions[questionIndex];return <Screen style={{maxWidth:680}}><Row><IconButton name="close" label="Stoppen met deze oefening" onPress={quit}/><View style={{flex:1,gap:8,marginLeft:6}}><Row style={{justifyContent:'space-between'}}><T variant="eyebrow">{sq3r?'STAP 5 VAN 5 · HERHALEN':autoQ?'INVULVRAGEN UIT JOUW TEKST':'WAT IS JE BIJGEBLEVEN?'}</T><T variant="caption">{questionIndex+1} van {passage.questions.length}</T></Row><ProgressBar value={(questionIndex+1)/passage.questions.length}/></View></Row><T variant="title" style={{fontSize:25,lineHeight:32}} accessibilityRole="header">{q.question}</T><View style={{gap:11}}>{q.options.map((o,i)=>{const right=reveal&&i===q.answer,wrong=reveal&&reveal.index===i&&!reveal.correct;return <Card key={i} onPress={()=>{if(picked!==null)return;const correct=i===q.answer;setPicked(i);setReveal({index:i,correct});app.answerQuestion(correct);if(correct){feel.done();setCelebrate('small');}else feel.tap();setTimeout(()=>{setPicked(null);setReveal(null);submitAnswer(i);},reduceMotion?500:correct?750:1300);}} accessibilityLabel={`${String.fromCharCode(65+i)}: ${o}`} style={{flexDirection:'row',alignItems:'center',gap:14,minHeight:64,paddingVertical:14,...(right?{borderColor:colors.accent,borderWidth:2,backgroundColor:ui.forestSoft}:wrong?{borderColor:ui.error,borderWidth:2}:picked===i?{borderColor:colors.accent,borderWidth:2}:null)}}><View style={s.optionCircle}><T variant="label" color={colors.accent}>{String.fromCharCode(65+i)}</T></View><T style={{flex:1}}>{o}</T><Icon name={right?'checkcircle':wrong?'close':'chevron'} size={17} color={right?colors.accent:wrong?ui.error:ui.dim}/></Card>;})}</View>{reveal&&<T variant="label" accessibilityLiveRegion="polite" color={reveal.correct?colors.accent:ui.muted} style={{textAlign:'center'}}>{reveal.correct?(state.answerStreak.current>=2?`Goed! ${state.answerStreak.current} goed op rij.`:'Goed!'):'Bijna. Het goede antwoord staat gemarkeerd.'}</T>}{celebrate&&<Celebration size={celebrate} onDone={()=>setCelebrate(null)}/>}{confirmExit&&<ExitConfirm onCancel={()=>{setConfirmExit(false);setPaused(false);}} onExit={onClose}/>}</Screen>;}
 const freeReading=!isPaced&&!isRest&&!isGame&&exercise.mode!=='scan'&&exercise.mode!=='paper'&&!(exercise.mode==='skim'&&variant==='previewing'&&previewStep===1)&&!(sq3r&&previewStep<3); const progress=isPaced?cursor/words.length:isRest?seconds/restLimit:isGame?round/10:exercise.mode==='scan'?round/scanTargets.length:exercise.mode==='paper'?(line+1)/paperLines.length:0;
 return <View style={{flex:1,backgroundColor:bg}}><View style={{width:'100%',maxWidth:940,alignSelf:'center',flex:1,paddingHorizontal:wide?30:22,paddingTop:18,paddingBottom:18}}><Row style={{marginBottom:14}}><IconButton name="close" label="Oefening sluiten" onPress={quit}/><View style={{flex:1,alignItems:'center',gap:2}}><T variant="label" color={readingInk(state.settings)}>{exercise.title}</T><T variant="caption">{request.daily?`${dailyStep+1} van ${steps} · `:''}{Math.floor(seconds/60)}:{String(Math.floor(seconds%60)).padStart(2,'0')}</T></View><IconButton name="info" label="Uitleg over deze oefening" onPress={()=>{setPaused(true);setInfo(true);}}/></Row>
 {isPaced?<Pressable accessibilityLabel="Toon leesbediening" onPress={revealControls} style={{flex:1,justifyContent:exercise.mode==='flow'?'flex-start':'center',alignItems:'center',gap:28,minHeight:250,overflow:'hidden',paddingTop:exercise.mode==='flow'?12:0}}>{pushRun&&<View><Pill label={sprinting?`SPRINT · ${pushWpm} WPM`:`TERUG NAAR JOUW TEMPO · ${tempo} WPM`} icon="zap" background={sprinting?colors.tintSun:ui.forestSoft}/></View>}<PacedReadingStage mode={exercise.mode==='innerstem'?'forward':exercise.mode==='push'?'chunks':exercise.mode} words={words} cursor={cursor} chunk={step} groupTarget={chunk} settings={state.settings} wide={wide}/>{exercise.mode!=='flow'&&<T variant="caption" style={{marginTop:32}}>{paused?'Even op adem komen.':`woord ${Math.min(cursor+1,words.length)} van ${words.length}`}</T>}</Pressable>:
 isRest?<View style={{flex:1,justifyContent:'center',alignItems:'center',gap:24,minHeight:340}}>{exercise.mode==='relax'?<RelaxStage variant={exercise.id==='palming'?'palming':'farnear'} seconds={seconds} paused={paused} voice={voice} ink={readingInk(state.settings)}/>:exercise.mode==='eye'?<EyeStage mode={eyeMode} speed={eyeSpeed} paused={paused} reduceMotion={reduceMotion} ramp={ramp} onTarget={onTarget}/>:<View style={{width:220,height:220,borderRadius:110,backgroundColor:ui.forestSoft,alignItems:'center',justifyContent:'center',transform:[{scale:reduceMotion?1:.9+Math.sin(seconds*Math.PI/4)*.08}]}}><View style={{width:160,height:160,borderRadius:80,backgroundColor:'#C8DDCC',alignItems:'center',justifyContent:'center'}}><Icon name="heart" size={45} color={colors.accent}/></View></View>}{exercise.mode!=='relax'&&<T variant="heading" color={readingInk(state.settings)}>{exercise.mode==='eye'?(eyeTargets?'Volg het doel. Een ster? Tik op Ster.':'Volg het puntje. Hoofd stil.'):seconds%8<4?'Adem rustig in.':'Adem rustig uit.'}</T>}{eyeTargets&&<View style={{width:'100%',gap:10}}><Button title={starFlash==='hit'?'Goed gezien!':starFlash==='miss'?'Geen ster…':'Ster!'} icon="star" onPress={tapStar} disabled={paused}/><T variant="caption" style={{textAlign:'center'}}>{stars.current.hits} van {stars.current.shown} {stars.current.shown===1?'ster':'sterren'} · {stars.current.wrong} keer mis</T></View>}{exercise.mode!=='relax'&&<T variant="caption">{Math.max(0,restLimit-Math.floor(seconds))} seconden{exercise.mode==='eye'&&ramp?' · het tempo loopt op':' voor jezelf'}</T>}</View>:
 exercise.mode==='peripheral'?<View style={{flex:1,justifyContent:'center',gap:16,paddingVertical:12}}><T variant="eyebrow" style={{textAlign:'center'}}>RONDE {round+1} VAN 10 · {spread}% · {flashMs} MS</T><T variant="caption" style={{textAlign:'center'}}>{roundFeedback?' ':peri==='ask'?'Welke twee woorden flitsten er?':'Houd je blik op het stipje.'}</T><PeripheralStage left={item.word} right={gameItems[(round+3)%10].word} spread={spread} visible={peri==='flash'&&!roundFeedback} dark={dark} lift={spread>=70?((round*37)%5-2)*24:0}/>{roundFeedback?<Row style={{justifyContent:'center',minHeight:120}}><Icon name={roundFeedback==='Goed gezien.'?'checkcircle':'eye'} color={colors.accent} size={30}/><T variant="heading" style={{textAlign:'center',fontSize:20}}>{roundFeedback}</T></Row>:peri==='ask'?<View style={{gap:10}}>{options.map((o,i)=><Button key={i} title={o} secondary onPress={()=>gameAnswer(o)} disabled={paused}/>)}</View>:<View style={{minHeight:120}}/>}</View>:
 isGame?<View style={{flex:1,justifyContent:'center',gap:25,paddingVertical:20}}><T variant="eyebrow" style={{textAlign:'center'}}>RONDE {round+1} VAN 10</T>{roundFeedback?<View style={{minHeight:250,alignItems:'center',justifyContent:'center',gap:18}}><Icon name={roundFeedback==='Goed gezien.'?'checkcircle':'eye'} color={colors.accent} size={48}/><T variant="heading" style={{textAlign:'center'}}>{roundFeedback}</T></View>:revealed&&exercise.mode!=='catcher'?<View style={{minHeight:250,justifyContent:'center',alignItems:'center',gap:20}}><T variant="caption">Kijk rustig naar de woorden.</T><T variant="heading" style={{fontSize:32,textAlign:'center'}}>{exercise.mode==='groups'?targetPair:item.word}</T></View>:<><T variant="heading" style={{textAlign:'center'}}>{exercise.mode==='catcher'?`Vind het woord: ${item.word}`:'Wat zag je net?'}</T><View style={{gap:12}}>{options.map((o,i)=><Button key={i} title={o} secondary onPress={()=>gameAnswer(o)} disabled={paused}/>)}</View></>}</View>:
 exercise.mode==='scan'?<View style={{flex:1,gap:20}}><Pill label={`ZOEK: ${scanTarget}`} icon="search"/><ScrollView><View style={{flexDirection:'row',flexWrap:'wrap',gap:4}}>{words.map((w,i)=><Pressable key={i} onPress={()=>scanAnswer(w)} accessibilityRole="button" accessibilityLabel={`Kies ${w}`} style={{paddingHorizontal:4,paddingVertical:9,minHeight:44}}><T style={{fontSize:18}}>{w}</T></Pressable>)}</View></ScrollView></View>:
 exercise.mode==='paper'?<View style={{flex:1,gap:18}}><T variant="heading">{passage.title}</T><ScrollView ref={paperScroll} style={{flex:1}} onLayout={e=>setPaperView(e.nativeEvent.layout.height)}><View style={{gap:16,paddingBottom:paperView*.6}}>{paperLines.map((p,i)=><Pressable key={i} accessibilityRole="button" accessibilityLabel={`Ga naar regel ${i+1}`} onPress={()=>!paused&&setLine(i)} onLayout={e=>{paperY.current[i]=e.nativeEvent.layout.y;}} style={{padding:14,borderRadius:12,backgroundColor:i===line?ui.forestSoft:'transparent',opacity:i<line?.4:1}}><ReadingText text={p} settings={state.settings}/></Pressable>)}</View></ScrollView>{guideAuto?<Row style={{gap:10,alignItems:'center'}}><IconButton name="minus" label="Gids langzamer" onPress={()=>setGuideWpm(w=>Math.max(80,w-20))}/><T variant="label" style={{flex:1,textAlign:'center'}}>{guideWpm} wpm</T><IconButton name="plus" label="Gids sneller" onPress={()=>setGuideWpm(w=>Math.min(600,w+20))}/><Button title="Klaar" secondary onPress={()=>finishReading(true)} disabled={paused}/></Row>:<Button title={line===paperLines.length-1?'Laatste regel gelezen':'Volgende regel'} secondary onPress={()=>line===paperLines.length-1?finishReading(true):setLine(line+1)} disabled={paused}/>}</View>:
 sq3r&&previewStep===2?<ScrollView style={{flex:1}} contentContainerStyle={{paddingVertical:24,gap:16}}><Pill label="STAP 2 VAN 5 · VRAGEN STELLEN" icon="help"/><T variant="heading" color={readingInk(state.settings)}>Wat wil je uit deze tekst halen?</T><T color={ui.muted}>Bedenk één vraag die de tekst voor je moet beantwoorden. Dat geeft je lezen een doel: je let vanzelf beter op.</T><TextInput accessibilityLabel="Jouw vraag aan de tekst" placeholder="Bijvoorbeeld: waarom gebeurt dit?" placeholderTextColor={ui.dim} value={sqQuestion} onChangeText={setSqQuestion} style={s.input} maxLength={200}/><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{[`Waar gaat ${passage.title.toLocaleLowerCase('nl')} over?`,'Wat is de belangrijkste oorzaak?','Wat kan ik hiermee?'].map(q=><Pressable key={q} accessibilityRole="button" onPress={()=>setSqQuestion(q)} style={s.suggest}><T variant="caption" color={colors.accent}>{q}</T></Pressable>)}</View></ScrollView>:<ScrollView style={{flex:1}} contentContainerStyle={{paddingVertical:24,paddingHorizontal:wide?50:2,gap:22}} scrollEventThrottle={120} onScroll={e=>measureRead({y:e.nativeEvent.contentOffset.y})} onLayout={e=>measureRead({view:e.nativeEvent.layout.height})} onContentSizeChange={(_,h)=>measureRead({content:h})}>{exercise.mode==='innerstem'&&<Row style={{justifyContent:'center',gap:14}}><Pill label="LEG DE NADRUK OP DE KERNWOORDEN" icon="volume"/></Row>}{exercise.mode==='skim'&&<Pill label={variant==='skimmen'?`HOOFDGEDACHTE · NOG ${Math.max(0,30-Math.floor(seconds))} SEC`:previewStep===1?`STAP 1${sq3r?' VAN 5':''} · VERKEN DE OPBOUW · NOG ${Math.max(0,30-Math.floor(seconds))} SEC`:sq3r?'STAP 3 VAN 5 · LEES DE HELE TEKST':'STAP 2 · LEES DE HELE TEKST'} icon="clock"/>}{sq3r&&previewStep===3&&!!sqQuestion.trim()&&<Card style={{gap:4,backgroundColor:ui.forestSoft,borderWidth:0,padding:14}}><T variant="caption">Jouw vraag</T><T variant="label">{sqQuestion}</T></Card>}<T variant="heading" color={readingInk(state.settings)}>{passage.title}</T>{exercise.mode==='skim'&&(variant==='skimmen'||previewStep===1)?paragraphs.map((p,i)=>{const first=firstSentence(p);return <View key={i} style={{gap:4}}><ReadingText text={first} settings={state.settings} style={{fontFamily:fonts.strong,color:dark?colors.sage:colors.accent}}/>{variant==='skimmen'&&p.length>first.length&&<ReadingText text={p.slice(first.length).trim()} settings={state.settings} style={{opacity:.55}}/>}</View>;}):paragraphs.map((p,i)=><Pressable key={i} onPress={()=>state.settings.lineGuide&&setLine(i)} style={{padding:state.settings.enabled&&state.settings.lineGuide?12:0,borderRadius:14,backgroundColor:state.settings.enabled&&state.settings.lineGuide&&i===line?ui.forestSoft:'transparent',opacity:state.settings.enabled&&state.settings.lineGuide&&i!==line?.45:1}}><ReadingText text={p} settings={state.settings}/></Pressable>)}</ScrollView>}
 {dayLesson&&!message&&<T variant="caption" style={{textAlign:'center',paddingTop:10}}>{dayLesson.hint}</T>}{!!message&&<T variant="caption" color={ui.error} accessibilityRole="alert" style={{padding:12,textAlign:'center'}}>{message}</T>}
 {freeReading?<View style={{gap:14,paddingTop:14}}><ProgressBar value={readProgress}/><Row style={{gap:12}}><IconButton name={paused?'play':'pause'} label={paused?'Verder lezen':'Pauzeren'} onPress={()=>{setPaused(!paused);setControlsVisible(true);}} style={{backgroundColor:ui.forestSoft}}/><Button title={exercise.mode==='skim'&&variant==='skimmen'?'Ik heb de hoofdgedachte':'Klaar met lezen'} icon="check" onPress={()=>finishReading(true)} disabled={paused} style={{flex:1}}/>{canSwap&&<IconButton name="refresh" label="Oefen met een andere tekst" onPress={()=>otherText(true)}/>}</Row></View>:<View style={{gap:16,paddingTop:18,opacity:isPaced&&!controlsVisible&&!paused?.45:1}}><ProgressBar value={progress}/>{canSwap&&<Pressable accessibilityRole="button" accessibilityLabel="Oefen met een andere tekst" onPress={()=>otherText(true)} style={{alignSelf:'center',flexDirection:'row',gap:8,alignItems:'center',minHeight:44,paddingHorizontal:12}}><Icon name="refresh" size={16} color={colors.accent}/><T variant="label" color={colors.accent} style={{fontSize:13}}>Andere tekst</T></Pressable>}<Row style={{justifyContent:'center',gap:26}}>{isPaced&&<IconButton name="minus" label="Langzamer lezen" onPress={()=>{tempoTouched.current=true;setTempo(Math.max(60,tempo-20));revealControls();}}/>}<IconButton name={paused?'play':'pause'} label={paused?'Verder lezen':'Pauzeren'} onPress={()=>{setPaused(!paused);setControlsVisible(true);}} style={{width:54,height:54,borderRadius:27,backgroundColor:ui.forestSoft}}/>{isPaced&&<IconButton name="plus" label="Sneller lezen" onPress={()=>{tempoTouched.current=true;setTempo(Math.min(800,tempo+20));revealControls();}}/>}{isPaced&&<View><T variant="stat" style={{fontSize:26}}>{pace}</T><T variant="caption">wpm</T></View>}</Row>{exercise.mode==='skim'&&variant==='previewing'&&previewStep===1?<Button title="Nu de volledige tekst lezen" secondary icon="arrow" onPress={()=>{setPreviewStep(2);activeMs.current=0;setSeconds(0);}} disabled={paused}/>:sq3r&&previewStep===1?<Button title="Klaar met verkennen" secondary icon="arrow" onPress={()=>setPreviewStep(2)} disabled={paused}/>:sq3r&&previewStep===2?<Button title="Stap 3: lees de hele tekst" icon="arrow" onPress={()=>{setPreviewStep(3);activeMs.current=0;setSeconds(0);}} disabled={paused}/>:!isRest&&!isGame&&exercise.mode!=='scan'&&exercise.mode!=='paper'&&<Button title={isPaced?'Eerder afronden':exercise.mode==='skim'&&variant==='skimmen'?'Ik heb de hoofdgedachte':'Klaar met lezen'} secondary onPress={()=>finishReading(!isPaced)} disabled={paused}/>}</View>}
 </View>{state.settings.enabled&&state.settings.overlay!=='none'&&<View pointerEvents="none" style={[StyleSheet.absoluteFill,{backgroundColor:overlayColors[state.settings.overlay],opacity:state.settings.overlayOpacity/100}]}/>}
 {paused&&!confirmExit&&!info&&<View style={s.pauseOverlay}><Card style={{gap:20,alignItems:'center',width:'85%',maxWidth:400}}><Icon name="pause" color={colors.accent} size={36}/><T variant="heading">Even pauze.</T><T variant="caption">Je oefentijd staat stil.</T><Button title="Ik ga weer verder" icon="play" onPress={()=>setPaused(false)} style={{alignSelf:'stretch'}}/><Button title="Stoppen met oefenen" secondary onPress={()=>setConfirmExit(true)} style={{alignSelf:'stretch'}}/></Card></View>}
 {info&&<View style={s.pauseOverlay}><Card style={{width:'85%',maxWidth:450,gap:18}}><T variant="heading">{exercise.title}</T><T>{exercise.description}</T><Button title="Verder met oefenen" onPress={()=>{setInfo(false);setPaused(false);}}/></Card></View>}
 {probe&&<MindProbe onAnswer={answerProbe}/>}{celebrate&&<Celebration size={celebrate} onDone={()=>setCelebrate(null)}/>}{confirmExit&&<ExitConfirm onCancel={()=>{setConfirmExit(false);setPaused(false);}} onExit={onClose}/>}
 </View>;
}
/** Laat zien of je op het aanbevolen tempo leest of op je eigen keuze, met een weg terug naar het advies. */
function TempoSource({tempo,recommended,onReset}:{tempo:number;recommended:number;onReset:()=>void}){const own=tempo!==recommended;return <Row style={{justifyContent:'space-between',flexWrap:'wrap'}}><Pill label={own?`EIGEN KEUZE · ADVIES ${recommended} WPM`:'AANBEVOLEN DOOR DE APP'} icon={own?'user':'sparkles'} background={own?colors.tintSun:ui.forestSoft}/>{own&&<Pressable accessibilityRole="button" onPress={onReset} style={{minHeight:44,justifyContent:'center'}}><T variant="label" color={colors.accent} style={{fontSize:13}}>Terug naar advies</T></Pressable>}</Row>;}
const PROBE_SECONDS=75;
function MindProbe({onAnswer}:{onAnswer:(wandered:boolean)=>void}){return <View style={s.pauseOverlay}><Card style={{width:'85%',maxWidth:420,gap:14}}><T variant="eyebrow">EVEN CHECKEN</T><T variant="heading">Was je er nog bij?</T><T color={ui.muted}>Eerlijk antwoorden helpt het meest. Iedereen dwaalt af; het gaat erom dat je het merkt.</T><Button title="Ja, ik las mee" onPress={()=>onAnswer(false)}/><Button title="Ik was even weg" secondary onPress={()=>onAnswer(true)}/></Card></View>;}
function ExitConfirm({onCancel,onExit}:{onCancel:()=>void;onExit:()=>void}){return <View style={s.pauseOverlay}><Card style={{width:'85%',maxWidth:420,gap:18}}><T variant="heading">Voor nu genoeg?</T><T color={ui.muted}>Deze oefening is nog niet afgerond en wordt niet bewaard. Eerder voltooide oefeningen blijven staan.</T><Button title="Verder met oefenen" onPress={onCancel}/><Button title="Stop voor nu" secondary onPress={onExit}/></Card></View>;}
const s=themed(()=>({input:{fontFamily:fonts.body,fontSize:16,padding:14,borderRadius:14,borderWidth:1,borderColor:ui.line,backgroundColor:ui.subtle,color:colors.ink,minHeight:50},suggest:{paddingHorizontal:12,paddingVertical:8,minHeight:36,justifyContent:'center',borderRadius:16,backgroundColor:ui.forestSoft},fixation:{width:24,height:2,borderRadius:2,backgroundColor:'#B9C8BF'},optionCircle:{width:34,height:34,borderRadius:17,backgroundColor:ui.forestSoft,alignItems:'center',justifyContent:'center'},pauseOverlay:{position:'absolute',top:0,right:0,bottom:0,left:0,backgroundColor:'rgba(15,26,20,.28)',justifyContent:'center',alignItems:'center',zIndex:20}}));
